const $=id=>document.getElementById(id);const API_URL=(window.APP_CONFIG?.apiUrl||'').trim();const apiConfigured=()=>API_URL&&!API_URL.includes('INCOLLA_QUI');
const journeyItems=[
{id:'birth-registration',phase:'nascita',group:'Pratiche',title:'Registrazione, codice fiscale e pediatra',meta:'Primi giorni',description:'Completare registrazione della nascita, tessera sanitaria e scelta del pediatra.'},
{id:'medical-folder',phase:'nascita',group:'Salute',title:'Creare la cartella sanitaria',meta:'Primo mese',description:'Raccogliere diagnosi, dimissioni, esami, visite e prescrizioni.'},
{id:'inps-start',phase:'nascita',group:'Invalidità civile e 104',title:'Avviare invalidità civile e Legge 104',meta:'Dopo la documentazione medica',description:'Preparare certificato introduttivo e domanda INPS.'},
{id:'specialist-checks',phase:'0-3',group:'Salute',title:'Programmare i controlli specialistici',meta:'0–3 anni',description:'Seguire il piano indicato da pediatra e centro di riferimento.'},
{id:'early-intervention',phase:'0-3',group:'Terapie e riabilitazione',title:'Attivare la presa in carico precoce',meta:'0–3 anni',description:'Valutare fisioterapia, logopedia e neuropsicomotricità.'},
{id:'allowances',phase:'0-3',group:'Invalidità civile e 104',title:'Verificare prestazioni economiche',meta:'Dopo i verbali',description:'Controllare indennità, Assegno Unico e contributi locali.'},
{id:'nursery',phase:'0-3',group:'Scuola e PEI',title:'Organizzare nido e assistenza educativa',meta:'Prima dell’inserimento',description:'Verificare servizi, priorità ed eventuale assistenza.'},
{id:'preschool-pei',phase:'3-6',group:'Scuola e PEI',title:'Preparare l’ingresso alla scuola dell’infanzia',meta:'3–6 anni',description:'Consegnare documentazione e partecipare alla definizione del PEI.'},
{id:'school-support',phase:'3-6',group:'Scuola e PEI',title:'Verificare sostegno e assistenza',meta:'Ogni anno scolastico',description:'Controllare ore di sostegno, assistenza, trasporto e ausili.'},
{id:'primary-pei',phase:'6-13',group:'Scuola e PEI',title:'Aggiornare annualmente il PEI',meta:'6–13 anni',description:'Definire obiettivi, autonomie, strumenti e verifiche.'},
{id:'tax-benefits',phase:'6-13',group:'Invalidità civile e 104',title:'Controllare agevolazioni fiscali',meta:'Ogni anno',description:'Verificare detrazioni, IVA agevolata e spese sanitarie.'},
{id:'autonomy',phase:'14-18',group:'Autonomia',title:'Costruire un progetto di autonomia',meta:'14–18 anni',description:'Lavorare su mobilità, denaro, cura personale e vita quotidiana.'},
{id:'orientation',phase:'14-18',group:'Scuola e PEI',title:'Pianificare scuola, formazione e lavoro',meta:'Scuola superiore',description:'Valutare orientamento, PCTO e formazione professionale.'},
{id:'age18',phase:'14-18',group:'Invalidità civile e 104',title:'Preparare il passaggio ai 18 anni',meta:'Tra 17 e 18 anni',description:'Verificare pratiche INPS, continuità sanitaria e tutele.'}
];
const defaultDocuments=['Certificato di nascita','Tessera sanitaria','Verbale invalidità civile','Verbale Legge 104','Referti specialistici','Prescrizioni riabilitative','PEI scolastico'];
const defaultBenefits=['Invalidità civile','Legge 104','Indennità di frequenza','Assegno Unico con disabilità','Permessi lavorativi','Agevolazioni fiscali e IVA'];
const emptyState=()=>({profile:null,completed:[],documents:defaultDocuments.map((name,i)=>({id:'doc-'+i,name,category:'Da classificare',done:false,date:''})),deadlines:[],health:[],school:[],benefits:defaultBenefits.map((title,i)=>({id:'ben-'+i,title,status:'Da verificare',notes:''})),expenses:[],diary:[]});
let state=Object.assign(emptyState(),JSON.parse(localStorage.getItem('pdp_state')||'{}'));let syncTimer=null,deferredPrompt=null;
function persist(sync=true){localStorage.setItem('pdp_state',JSON.stringify(state));renderAll();if(sync&&state.profile?.familyCode&&apiConfigured()){clearTimeout(syncTimer);setSyncStatus('Modifiche da sincronizzare');syncTimer=setTimeout(()=>syncToGoogle(false),800)}}
function snapshot(){return {...state,updatedAt:new Date().toISOString()}}
function setSyncStatus(text,type=''){if($('syncStatus'))$('syncStatus').textContent=text;if($('syncDot'))$('syncDot').className='sync-dot '+type}
async function syncToGoogle(show=true){if(!apiConfigured()){setSyncStatus('Configura Apps Script','error');if(show)alert('Inserisci in config.js l’URL /exec di Apps Script.');return}setSyncStatus('Sincronizzazione…');try{const r=await fetch(API_URL,{method:'POST',headers:{'Content-Type':'text/plain;charset=utf-8'},body:JSON.stringify({action:'save',familyCode:state.profile.familyCode,data:snapshot()})});const j=await r.json();if(!j.ok)throw new Error(j.error||'Errore');setSyncStatus('Salvato su Google','ok')}catch(e){setSyncStatus('Offline: copia locale','error');if(show)alert('Dati salvati sul dispositivo. Sincronizzazione non riuscita: '+e.message)}}
async function loadFromGoogle(show=true){if(!apiConfigured()||!state.profile?.familyCode)return;setSyncStatus('Scaricamento…');try{const r=await fetch(`${API_URL}?action=load&familyCode=${encodeURIComponent(state.profile.familyCode)}&_=${Date.now()}`,{cache:'no-store'});const j=await r.json();if(!j.ok)throw new Error(j.error||'Errore');if(j.found){state=Object.assign(emptyState(),j.data);localStorage.setItem('pdp_state',JSON.stringify(state));renderAll();setSyncStatus('Dati scaricati','ok');if(show)alert('Dati aggiornati dal Foglio Google.')}else setSyncStatus('Nuovo profilo')}catch(e){setSyncStatus('Errore collegamento','error');if(show)alert(e.message)}}
function ageText(date){if(!date)return'';const b=new Date(date+'T00:00:00'),t=new Date();if(b>t){const d=Math.ceil((b-t)/86400000);return`Nascita prevista tra circa ${d} giorni`}let y=t.getFullYear()-b.getFullYear(),m=t.getMonth()-b.getMonth();if(t.getDate()<b.getDate())m--;if(m<0){y--;m+=12}return y<1?`${Math.max(0,m)} mesi`:`${y} anni e ${Math.max(0,m)} mesi`}
function esc(s){return String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[c]))}
function fmtDate(d){return d?new Date(d+'T00:00:00').toLocaleDateString('it-IT'):'—'}
function uid(){return crypto.randomUUID?crypto.randomUUID():Date.now()+'-'+Math.random()}
function showView(id){document.querySelectorAll('.view').forEach(v=>v.classList.toggle('active-view',v.id===id));document.querySelectorAll('[data-view]').forEach(b=>b.classList.toggle('active',b.dataset.view===id));$('sidebar').classList.remove('open');window.scrollTo({top:0,behavior:'smooth'})}
function renderAll(){if(!state.profile){$('onboarding').classList.remove('hidden');$('app').classList.add('hidden');return}$('onboarding').classList.add('hidden');$('app').classList.remove('hidden');$('profileName').textContent=state.profile.childName;$('profileAge').textContent=ageText(state.profile.birthDate);$('profileBirth').textContent='Nato/a o data prevista: '+fmtDate(state.profile.birthDate);$('welcomeText').textContent=`Ciao, famiglia di ${state.profile.childName}! 👋`;renderJourney();renderDashboard();renderDeadlines();renderDocuments();renderSimpleList('healthList',state.health,'health');renderSimpleList('schoolList',state.school,'school');renderBenefits();renderExpenses();renderDiary();$('apiInfo').textContent=apiConfigured()?'Google Apps Script configurato.':'Google Apps Script non ancora configurato in config.js.'}
function renderDashboard(){
const today=new Date().toISOString().slice(0,10),future=[...state.deadlines].filter(x=>x.date>=today).sort((a,b)=>a.date.localeCompare(b.date));
$('metricCompleted').textContent=state.completed.length;
$('metricAppointments').textContent=future.length;
$('metricDocuments').textContent=state.documents.length;
$('metricBenefits').textContent=state.benefits.filter(x=>x.status==='Approvata').length;
const pending=journeyItems.filter(x=>!state.completed.includes(x.id)).slice(0,4);
$('todayList').innerHTML=pending.length?pending.map((x,i)=>`<div class="compact-item ${i===0?'is-urgent':i===1?'is-soon':''}"><input type="checkbox" data-check="${x.id}" aria-label="Completa ${esc(x.title)}"><div class="grow"><strong>${esc(x.title)}</strong><br><small>${esc(x.group)} · ${esc(x.meta)}</small></div><span class="badge ${i===0?'urgent':i===1?'soon':''}">${i===0?'Priorità':i===1?'Prossima':'Da fare'}</span></div>`).join(''):'<div class="empty-state">Hai completato tutte le attività della checklist.</div>';
const upcoming=future.slice(0,3);
$('nextAppointments').innerHTML=upcoming.length?upcoming.map(x=>{const d=new Date(x.date+'T00:00:00');return`<div class="compact-item"><div class="date-box"><strong>${d.getDate()}</strong>${d.toLocaleDateString('it-IT',{month:'short'}).toUpperCase()}</div><div class="grow"><strong>${esc(x.title)}</strong><br><small>${esc(x.category||'Appuntamento')} ${esc(x.time||'')}</small></div></div>`}).join(''):'<div class="empty-state">Nessun appuntamento futuro.</div>';
const groups=[...new Set(journeyItems.map(x=>x.group))].slice(0,4);
$('progressList').innerHTML=groups.map(g=>{const all=journeyItems.filter(x=>x.group===g),done=all.filter(x=>state.completed.includes(x.id)).length,pct=Math.round(done/all.length*100);return`<div class="progress-block"><div class="progress-label"><span>${esc(g)}</span><span>${done}/${all.length}</span></div><div class="progress-track" aria-label="${esc(g)} ${pct}%"><div class="progress-bar" style="width:${pct}%"></div></div></div>`}).join('');
$('recentDocs').innerHTML=state.documents.slice(-4).reverse().map(x=>`<div class="doc-chip"><div class="doc-icon">📄</div><strong>${esc(x.name)}</strong><br><small>${esc(x.category||'Documento')}</small></div>`).join('')||'<div class="empty-state">Nessun documento.</div>';
document.querySelectorAll('[data-check]').forEach(c=>c.onchange=()=>toggleCompleted(c.dataset.check))}
function toggleCompleted(id){state.completed=state.completed.includes(id)?state.completed.filter(x=>x!==id):[...state.completed,id];persist()}
function renderJourney(){const f=$('phaseFilter').value;$('journeyList').innerHTML=journeyItems.filter(x=>f==='all'||x.phase===f).map(x=>`<article class="data-card ${state.completed.includes(x.id)?'completed':''}"><div class="check-row"><input type="checkbox" data-journey="${x.id}" ${state.completed.includes(x.id)?'checked':''}><div class="card-main"><h3>${esc(x.title)}</h3><small>${esc(x.group)} · ${esc(x.meta)}</small><p>${esc(x.description)}</p></div></div></article>`).join('');document.querySelectorAll('[data-journey]').forEach(c=>c.onchange=()=>toggleCompleted(c.dataset.journey))}
function renderDeadlines(){$('deadlineList').innerHTML=[...state.deadlines].sort((a,b)=>a.date.localeCompare(b.date)).map(x=>`<article class="data-card"><div class="date-box"><strong>${new Date(x.date+'T00:00:00').getDate()}</strong>${new Date(x.date+'T00:00:00').toLocaleDateString('it-IT',{month:'short'}).toUpperCase()}</div><div class="card-main"><h3>${esc(x.title)}</h3><small>${esc(x.category)} · ${esc(x.time||'Orario non indicato')}</small><p>${esc(x.notes||'')}</p></div><div class="card-actions"><button data-del-deadline="${x.id}">🗑️</button></div></article>`).join('')||'<p>Nessuna scadenza salvata.</p>';document.querySelectorAll('[data-del-deadline]').forEach(b=>b.onclick=()=>{state.deadlines=state.deadlines.filter(x=>x.id!==b.dataset.delDeadline);persist()})}
function renderDocuments(){$('documentList').innerHTML=state.documents.map(x=>`<article class="data-card ${x.done?'completed':''}"><div class="doc-icon">📄</div><div class="card-main"><h3>${esc(x.name)}</h3><small>${esc(x.category||'Documento')}</small></div><div class="card-actions"><button data-doc-toggle="${x.id}">${x.done?'↩️':'✅'}</button><button data-doc-del="${x.id}">🗑️</button></div></article>`).join('');document.querySelectorAll('[data-doc-toggle]').forEach(b=>b.onclick=()=>{const x=state.documents.find(d=>d.id===b.dataset.docToggle);x.done=!x.done;persist()});document.querySelectorAll('[data-doc-del]').forEach(b=>b.onclick=()=>{state.documents=state.documents.filter(x=>x.id!==b.dataset.docDel);persist()})}
function renderSimpleList(target,arr,key){$(target).innerHTML=arr.map(x=>`<article class="data-card"><div class="doc-icon">${key==='health'?'❤️':'🎓'}</div><div class="card-main"><h3>${esc(x.title)}</h3><small>${esc(x.type||x.year||'')}</small><p>${esc(x.notes||'')}</p></div><div class="card-actions"><button data-simple-del="${key}|${x.id}">🗑️</button></div></article>`).join('')||'<p>Nessun elemento inserito.</p>';document.querySelectorAll('[data-simple-del]').forEach(b=>b.onclick=()=>{const [k,id]=b.dataset.simpleDel.split('|');state[k]=state[k].filter(x=>x.id!==id);persist()})}
function renderBenefits(){$('benefitsList').innerHTML=state.benefits.map(x=>`<article class="data-card"><div class="doc-icon">🎁</div><div class="card-main"><h3>${esc(x.title)}</h3><span class="badge">${esc(x.status)}</span><p>${esc(x.notes||'')}</p></div><select data-benefit="${x.id}"><option ${x.status==='Da verificare'?'selected':''}>Da verificare</option><option ${x.status==='Da richiedere'?'selected':''}>Da richiedere</option><option ${x.status==='Richiesta inviata'?'selected':''}>Richiesta inviata</option><option ${x.status==='Approvata'?'selected':''}>Approvata</option></select></article>`).join('');document.querySelectorAll('[data-benefit]').forEach(s=>s.onchange=()=>{state.benefits.find(x=>x.id===s.dataset.benefit).status=s.value;persist()})}
function renderExpenses(){const total=state.expenses.reduce((a,x)=>a+Number(x.amount||0),0);$('expenseTotal').textContent=total.toLocaleString('it-IT',{style:'currency',currency:'EUR'});$('expenseList').innerHTML=[...state.expenses].sort((a,b)=>b.date.localeCompare(a.date)).map(x=>`<article class="data-card"><div class="doc-icon">💶</div><div class="card-main"><h3>${esc(x.title)}</h3><small>${fmtDate(x.date)} · ${esc(x.category)}</small></div><strong>${Number(x.amount).toLocaleString('it-IT',{style:'currency',currency:'EUR'})}</strong><div class="card-actions"><button data-exp-del="${x.id}">🗑️</button></div></article>`).join('')||'<p>Nessuna spesa registrata.</p>';document.querySelectorAll('[data-exp-del]').forEach(b=>b.onclick=()=>{state.expenses=state.expenses.filter(x=>x.id!==b.dataset.expDel);persist()})}
function renderDiary(){$('diaryList').innerHTML=[...state.diary].sort((a,b)=>b.date.localeCompare(a.date)).map(x=>`<article class="data-card"><div class="doc-icon">⭐</div><div class="card-main"><h3>${esc(x.title)}</h3><small>${fmtDate(x.date)}</small><p>${esc(x.text)}</p></div><div class="card-actions"><button data-dia-del="${x.id}">🗑️</button></div></article>`).join('')||'<p>Il diario è ancora vuoto.</p>';document.querySelectorAll('[data-dia-del]').forEach(b=>b.onclick=()=>{state.diary=state.diary.filter(x=>x.id!==b.dataset.diaDel);persist()})}
$('profileForm').onsubmit=e=>{e.preventDefault();state.profile={childName:$('childName').value.trim(),familyCode:$('familyCode').value.trim().toUpperCase(),birthDate:$('birthDate').value};persist(false);renderAll();syncToGoogle(false)};
document.querySelectorAll('[data-view]').forEach(b=>b.onclick=()=>showView(b.dataset.view));document.querySelectorAll('[data-view-target]').forEach(b=>b.onclick=()=>showView(b.dataset.viewTarget));$('menuBtn').onclick=()=>$('sidebar').classList.toggle('open');$('phaseFilter').onchange=renderJourney;$('syncBtn').onclick=()=>syncToGoogle(true);$('bottomSync').onclick=()=>syncToGoogle(true);$('reloadBtn').onclick=()=>loadFromGoogle(true);
$('deadlineForm').onsubmit=e=>{e.preventDefault();state.deadlines.push({id:uid(),title:$('deadlineTitle').value.trim(),date:$('deadlineDate').value,time:$('deadlineTime').value,category:$('deadlineCategory').value,notes:$('deadlineNotes').value.trim()});e.target.reset();persist()};
$('documentForm').onsubmit=e=>{e.preventDefault();state.documents.push({id:uid(),name:$('documentName').value.trim(),category:$('documentCategory').value,done:false,date:new Date().toISOString().slice(0,10)});e.target.reset();persist()};
$('healthForm').onsubmit=e=>{e.preventDefault();state.health.push({id:uid(),title:$('healthTitle').value.trim(),type:$('healthType').value,notes:$('healthNotes').value.trim()});e.target.reset();persist()};
$('schoolForm').onsubmit=e=>{e.preventDefault();state.school.push({id:uid(),title:$('schoolTitle').value.trim(),year:$('schoolYear').value.trim(),notes:$('schoolNotes').value.trim()});e.target.reset();persist()};
$('expenseForm').onsubmit=e=>{e.preventDefault();state.expenses.push({id:uid(),title:$('expenseTitle').value.trim(),amount:Number($('expenseAmount').value),date:$('expenseDate').value,category:$('expenseCategory').value});e.target.reset();persist()};
$('diaryForm').onsubmit=e=>{e.preventDefault();state.diary.push({id:uid(),title:$('diaryTitle').value.trim(),date:$('diaryDate').value,text:$('diaryText').value.trim()});e.target.reset();persist()};
$('editProfileBtn').onclick=()=>{if(!state.profile)return;$('childName').value=state.profile.childName;$('familyCode').value=state.profile.familyCode;$('birthDate').value=state.profile.birthDate;$('app').classList.add('hidden');$('onboarding').classList.remove('hidden')};$('resetBtn').onclick=()=>{if(confirm('Cancellare tutti i dati salvati su questo dispositivo?')){localStorage.removeItem('pdp_state');location.reload()}};
window.addEventListener('beforeinstallprompt',e=>{e.preventDefault();deferredPrompt=e;$('installBtn').classList.remove('hidden')});$('installBtn').onclick=async()=>{if(deferredPrompt){deferredPrompt.prompt();await deferredPrompt.userChoice;deferredPrompt=null}};if('serviceWorker'in navigator)window.addEventListener('load',()=>navigator.serviceWorker.register('service-worker.js'));window.addEventListener('online',()=>syncToGoogle(false));window.addEventListener('offline',()=>setSyncStatus('Offline: copia locale','error'));
renderAll();if(state.profile){setSyncStatus(apiConfigured()?'Google collegato':'Configura Apps Script',apiConfigured()?'ok':'error');loadFromGoogle(false)}
