const $=id=>document.getElementById(id);const API_URL=(window.APP_CONFIG?.apiUrl||'').trim();const apiConfigured=()=>API_URL&&!API_URL.includes('INCOLLA_QUI');
const defaultBirthPrep=[
{id:'prep-doc-id',category:'Documenti',title:'Controllare documenti di identità e tessera sanitaria',daysBefore:90,priority:'Alta'},
{id:'prep-folder',category:'Documenti',title:'Preparare la cartella con esami, ecografie e referti',daysBefore:60,priority:'Alta'},
{id:'prep-hospital-info',category:'Ospedale',title:'Verificare indicazioni e lista richiesta dal punto nascita',daysBefore:75,priority:'Alta'},
{id:'prep-mother-bag',category:'Valigia mamma',title:'Preparare cambi, igiene personale e documenti della mamma',daysBefore:45,priority:'Alta'},
{id:'prep-baby-bag',category:'Valigia bambino',title:'Preparare body, tutine, cappellino e copertina',daysBefore:45,priority:'Alta'},
{id:'prep-companion-bag',category:'Accompagnatore',title:'Preparare cambio, caricabatterie, acqua e piccoli snack',daysBefore:30,priority:'Media'},
{id:'prep-car-seat',category:'Casa e rientro',title:'Installare e controllare il seggiolino auto',daysBefore:30,priority:'Alta'},
{id:'prep-sleep',category:'Casa e rientro',title:'Preparare uno spazio sicuro per il sonno del neonato',daysBefore:30,priority:'Alta'},
{id:'prep-pediatrician',category:'Prime settimane',title:'Informarsi sulla scelta del pediatra e sui contatti utili',daysBefore:30,priority:'Media'},
{id:'prep-contacts',category:'Organizzazione',title:'Salvare i contatti del reparto e definire chi avvisare',daysBefore:21,priority:'Media'}
];
const pregnancyItems=[
{id:'preg-w12',phase:'gravidanza',week:12,group:'Gravidanza',title:'Raccogliere esami ed ecografie',meta:'Entro la 12ª settimana',description:'Conservare in un unico posto referti, analisi ed ecografie già effettuate.'},
{id:'preg-questions',phase:'gravidanza',week:16,group:'Preparazione visite',title:'Preparare le domande per il ginecologo',meta:'Dalla 16ª settimana',description:'Annotare dubbi, farmaci assunti e domande da portare al prossimo controllo.'},
{id:'preg-morphology',phase:'gravidanza',week:18,group:'Controlli',title:'Programmare la morfologica',meta:'Generalmente tra 19ª e 21ª settimana',description:'Verificare con il ginecologo la data più adatta e le indicazioni personali.'},
{id:'preg-baby-center',phase:'gravidanza',week:20,group:'Organizzazione',title:'Individuare il centro pediatrico di riferimento',meta:'Dal secondo trimestre',description:'Salvare contatti e indicazioni ricevute dai professionisti che seguono la gravidanza.'},
{id:'preg-diary',phase:'gravidanza',week:22,group:'Diario',title:'Scrivere un ricordo della gravidanza',meta:'Quando desiderate',description:'Annotare emozioni, momenti speciali e pensieri da conservare.'},
{id:'preg-documents',phase:'gravidanza',week:28,group:'Documenti',title:'Preparare la cartella per l’ospedale',meta:'Terzo trimestre',description:'Raccogliere documenti personali, esami, ecografie e indicazioni cliniche.'},
{id:'preg-bag',phase:'gravidanza',week:32,group:'Preparazione parto',title:'Preparare la valigia per il parto',meta:'Tra 32ª e 36ª settimana',description:'Preparare quanto richiesto dalla struttura scelta per mamma e neonato.'},
{id:'preg-birth-plan',phase:'gravidanza',week:36,group:'Preparazione parto',title:'Confermare contatti e piano per il parto',meta:'Ultime settimane',description:'Verificare percorso, numeri utili, accompagnatore e modalità di accesso alla struttura.'}
];
const allJourneyItems=()=>state?.profile?.mode==='pregnancy'?[...pregnancyItems,...journeyItems]:journeyItems;
const journeyItems=[
{id:'birth-registration',phase:'nascita',group:'Pratiche',title:'Registrazione, codice fiscale e pediatra',meta:'Primi giorni',description:'Completare registrazione della nascita, tessera sanitaria e scelta del pediatra.'},
{id:'medical-folder',phase:'nascita',group:'Salute',title:'Creare la cartella sanitaria',meta:'Primo mese',description:'Raccogliere diagnosi, dimissioni, esami, visite e prescrizioni.'},
{id:'inps-start',phase:'nascita',group:'Invalidità civile e 104',title:'Avviare invalidità civile e Legge 104',meta:'Dopo la documentazione medica',description:'Preparare certificato introduttivo e domanda INPS.'},
{id:'specialist-checks',phase:'0-3',group:'Salute',title:'Programmare i controlli specialistici',meta:'0–3 anni',description:'Seguire il piano indicato da pediatra e centro di riferimento.'},
{id:'early-intervention',phase:'0-3',group:'Terapie e riabilitazione',title:'Attivare la presa in carico precoce',meta:'0–3 anni',description:'Valutare fisioterapia, logopedia e neuropsicomotricità.'},
{id:'allowances',phase:'0-3',group:'Invalidità civile e 104',title:'Verificare prestazioni economiche',meta:'Dopo i verbali',description:'Controllare indennità, Assegno Unico e contributi locali.'},
{id:'nursery',phase:'0-3',group:'Scuola e PEI',title:'Organizzare nido e assistenza educativa',meta:'Prima dell’inserimento',description:'Verificare servizi, priorità ed eventuale assistenza.'},
{id:'preschool-pei',phase:'3-6',group:'Scuola e PEI',title:'Preparare l’ingresso alla scuola dell’infanzia',meta:'3–6 anni',description:'Consegnare documentazione e partecipare alla definizione del PEI.'},
{id:'school-support',phase:'3-6',group:'Scuola e PEI',title:'Verificare sostegno e assistenza',meta:'Ogni anno scolastico',description:'Controllare ore di sostegno, assistenza, trasporto e ausili.'},
{id:'primary-pei',phase:'6-13',group:'Scuola e PEI',title:'Aggiornare annualmente il PEI',meta:'6–13 anni',description:'Definire obiettivi, autonomie, strumenti e verifiche.'},
{id:'tax-benefits',phase:'6-13',group:'Invalidità civile e 104',title:'Controllare agevolazioni fiscali',meta:'Ogni anno',description:'Verificare detrazioni, IVA agevolata e spese sanitarie.'},
{id:'autonomy',phase:'14-18',group:'Autonomia',title:'Costruire un progetto di autonomia',meta:'14–18 anni',description:'Lavorare su mobilità, denaro, cura personale e vita quotidiana.'},
{id:'orientation',phase:'14-18',group:'Scuola e PEI',title:'Pianificare scuola, formazione e lavoro',meta:'Scuola superiore',description:'Valutare orientamento, PCTO e formazione professionale.'},
{id:'age18',phase:'14-18',group:'Invalidità civile e 104',title:'Preparare il passaggio ai 18 anni',meta:'Tra 17 e 18 anni',description:'Verificare pratiche INPS, continuità sanitaria e tutele.'}
];
const defaultDocuments=['Certificato di nascita','Tessera sanitaria','Verbale invalidità civile','Verbale Legge 104','Referti specialistici','Prescrizioni riabilitative','PEI scolastico'];
const defaultBenefits=['Invalidità civile','Legge 104','Indennità di frequenza','Assegno Unico con disabilità','Permessi lavorativi','Agevolazioni fiscali e IVA'];
const emptyState=()=>({profile:null,completed:[],documents:defaultDocuments.map((name,i)=>({id:'doc-'+i,name,category:'Da classificare',status:'Manca',done:false,date:'',expiry:'',visitId:'',notes:''})),deadlines:[],health:[],school:[],benefits:defaultBenefits.map((title,i)=>({id:'ben-'+i,title,status:'Da verificare',notes:''})),expenses:[],diary:[],pregnancyNotes:[],visits:[],birthPrep:defaultBirthPrep.map(x=>({...x,done:false,custom:false,notes:''}))});
let state=Object.assign(emptyState(),JSON.parse(localStorage.getItem('pdp_state')||'{}'));state.documents=(state.documents||[]).map(d=>({...d,status:d.status||(d.done?'Completo':'Manca'),done:(d.status?d.status==='Completo':!!d.done),expiry:d.expiry||'',visitId:d.visitId||'',notes:d.notes||''}));let syncTimer=null,deferredPrompt=null;
function persist(sync=true){localStorage.setItem('pdp_state',JSON.stringify(state));renderAll();if(sync&&state.profile?.familyCode&&apiConfigured()){clearTimeout(syncTimer);setSyncStatus('Modifiche da sincronizzare');syncTimer=setTimeout(()=>syncToGoogle(false),800)}}
function snapshot(){return {...state,updatedAt:new Date().toISOString()}}
function setSyncStatus(text,type=''){if($('syncStatus'))$('syncStatus').textContent=text;if($('syncDot'))$('syncDot').className='sync-dot '+type}
async function syncToGoogle(show=true){if(!apiConfigured()){setSyncStatus('Configura Apps Script','error');if(show)alert('Inserisci in config.js l’URL /exec di Apps Script.');return}setSyncStatus('Sincronizzazione…');try{const r=await fetch(API_URL,{method:'POST',headers:{'Content-Type':'text/plain;charset=utf-8'},body:JSON.stringify({action:'save',familyCode:state.profile.familyCode,data:snapshot()})});const j=await r.json();if(!j.ok)throw new Error(j.error||'Errore');setSyncStatus('Salvato su Google','ok')}catch(e){setSyncStatus('Offline: copia locale','error');if(show)alert('Dati salvati sul dispositivo. Sincronizzazione non riuscita: '+e.message)}}
async function loadFromGoogle(show=true){if(!apiConfigured()||!state.profile?.familyCode)return;setSyncStatus('Scaricamento…');try{const r=await fetch(`${API_URL}?action=load&familyCode=${encodeURIComponent(state.profile.familyCode)}&_=${Date.now()}`,{cache:'no-store'});const j=await r.json();if(!j.ok)throw new Error(j.error||'Errore');if(j.found){state=Object.assign(emptyState(),j.data);localStorage.setItem('pdp_state',JSON.stringify(state));renderAll();setSyncStatus('Dati scaricati','ok');if(show)alert('Dati aggiornati dal Foglio Google.')}else setSyncStatus('Nuovo profilo')}catch(e){setSyncStatus('Errore collegamento','error');if(show)alert(e.message)}}
function ageText(date){if(!date)return'';const b=new Date(date+'T00:00:00'),t=new Date();if(b>t){const d=Math.ceil((b-t)/86400000);return`Nascita prevista tra circa ${d} giorni`}let y=t.getFullYear()-b.getFullYear(),m=t.getMonth()-b.getMonth();if(t.getDate()<b.getDate())m--;if(m<0){y--;m+=12}return y<1?`${Math.max(0,m)} mesi`:`${y} anni e ${Math.max(0,m)} mesi`}
function esc(s){return String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[c]))}
function fmtDate(d){return d?new Date(d+'T00:00:00').toLocaleDateString('it-IT'):'—'}
function uid(){return crypto.randomUUID?crypto.randomUUID():Date.now()+'-'+Math.random()}
function showView(id){document.querySelectorAll('.view').forEach(v=>v.classList.toggle('active-view',v.id===id));document.querySelectorAll('[data-view]').forEach(b=>b.classList.toggle('active',b.dataset.view===id));$('sidebar').classList.remove('open');window.scrollTo({top:0,behavior:'smooth'})}
function renderAll(){if(!state.profile){$('onboarding').classList.remove('hidden');$('app').classList.add('hidden');return}$('onboarding').classList.add('hidden');$('app').classList.remove('hidden');$('profileName').textContent=state.profile.childName;$('profileAge').textContent=state.profile.mode==='pregnancy'?pregnancyLabel(state.profile.birthDate):ageText(state.profile.birthDate);$('profileBirth').textContent=(state.profile.mode==='pregnancy'?'Data presunta del parto: ':'Data di nascita: ')+fmtDate(state.profile.birthDate);$('welcomeText').textContent=state.profile.mode==='pregnancy'?`In attesa di ${state.profile.childName} ❤️`:`Ciao, famiglia di ${state.profile.childName}! 👋`;renderPregnancy();renderJourney();renderTimeline();renderDashboard();renderDeadlines();renderVisits();renderDocuments();renderSimpleList('healthList',state.health,'health');renderSimpleList('schoolList',state.school,'school');renderBenefits();renderExpenses();renderDiary();renderPregnancyDiary();renderBirthPrep();$('apiInfo').textContent=apiConfigured()?'Google Apps Script configurato.':'Google Apps Script non ancora configurato in config.js.'}
function pregnancyInfo(dueDate){const due=new Date(dueDate+'T00:00:00'),now=new Date();const conception=new Date(due);conception.setDate(conception.getDate()-280);const elapsed=Math.floor((now-conception)/86400000);const week=Math.max(1,Math.min(40,Math.floor(elapsed/7)+1));const daysLeft=Math.max(0,Math.ceil((due-now)/86400000));return{week,daysLeft,pct:Math.max(2,Math.min(100,Math.round(elapsed/280*100)))}}
function pregnancyLabel(date){const i=pregnancyInfo(date);return`${i.week}ª settimana di gravidanza`}
function activeItems(){if(state.profile?.mode!=='pregnancy')return journeyItems;const w=pregnancyInfo(state.profile.birthDate).week;return pregnancyItems.filter(x=>x.week<=w+6)}
function nextJourneyItem(){const items=state.profile?.mode==='pregnancy'?activeItems():journeyItems;return items.find(x=>!state.completed.includes(x.id))||null}
function renderPregnancy(){const box=$('pregnancyHero');if(!box)return;if(state.profile.mode!=='pregnancy'){box.classList.add('hidden');return}box.classList.remove('hidden');const i=pregnancyInfo(state.profile.birthDate),next=nextJourneyItem();$('pregnancyWeek').textContent=`${i.week}ª settimana di gravidanza`;$('pregnancyCountdown').textContent=i.daysLeft?`Mancano circa ${i.daysLeft} giorni alla data presunta del parto.`:'La data presunta del parto è arrivata.';$('pregnancyBar').style.width=i.pct+'%';$('pregnancyProgressText').textContent=`Percorso completato al ${i.pct}% · data presunta ${fmtDate(state.profile.birthDate)}`;$('nextStepTitle').textContent=next?.title||'Avete completato le tappe disponibili';$('nextStepMeta').textContent=next?`${next.meta} · circa 5 minuti`:'Continuate ad aggiornare diario e appuntamenti';$('startNextStep').onclick=()=>showView(next?.group==='Diario'?'diario':'checklist')}
function renderTimeline(){if(!$('journeyTimeline'))return;const isPreg=state.profile.mode==='pregnancy',info=isPreg?pregnancyInfo(state.profile.birthDate):null;const items=isPreg?pregnancyItems:journeyItems;$('journeySubtitle').textContent=isPreg?`Siete alla ${info.week}ª settimana. Le indicazioni sanitarie vanno sempre concordate con i professionisti che seguono la gravidanza.`:'Dalla nascita ai 18 anni, con le vostre tappe.';$('journeyTimeline').innerHTML=items.map(x=>{const done=state.completed.includes(x.id),current=isPreg&&!done&&x.week<=info.week+2&&x.week>=info.week-2;return`<div class="timeline-item ${done?'done':current?'current':''}"><span class="timeline-dot"></span><div class="timeline-card"><h3>${done?'✓ ':''}${esc(x.title)}</h3><small>${esc(x.meta)}</small><p>${esc(x.description)}</p>${!done?`<button class="soft-btn" data-timeline-check="${x.id}">Segna come completato</button>`:''}</div></div>`}).join('');document.querySelectorAll('[data-timeline-check]').forEach(b=>b.onclick=()=>toggleCompleted(b.dataset.timelineCheck))}
function daysBetweenToday(date){const today=new Date();today.setHours(0,0,0,0);const d=new Date(date+'T00:00:00');return Math.ceil((d-today)/86400000)}
function getTodayPriority(){
 const today=new Date().toISOString().slice(0,10);
 const visits=(state.visits||[]).filter(v=>v.date>=today).sort((a,b)=>a.date.localeCompare(b.date));
 const nextVisit=visits[0];
 if(nextVisit){const days=daysBetweenToday(nextVisit.date);if(days<=7){const missing=[];if(!nextVisit.documents)missing.push('preparare i documenti da portare');if(!nextVisit.questions)missing.push('scrivere le domande da fare');if(missing.length)return{level:days<=2?'Urgente':'Prossima',title:days===0?'La visita è oggi':days===1?'La visita è domani':`Visita tra ${days} giorni`,message:`${nextVisit.title}${nextVisit.specialist?' · '+nextVisit.specialist:''}`,details:missing.map(x=>'⬜ '+x),time:'circa 10 minuti',view:'visite'};return{level:days<=2?'Urgente':'Prossima',title:days===0?'La visita è oggi':days===1?'La visita è domani':`Prepariamo la visita tra ${days} giorni`,message:nextVisit.title,details:['✔ Documenti da portare registrati','✔ Domande già preparate'],time:'circa 5 minuti',view:'visite'}}}
 if(state.profile?.mode==='pregnancy'){
  const due=pregnancyInfo(state.profile.birthDate),prep=(state.birthPrep||[]).find(x=>!x.done&&birthPrepAvailable(x));
  if(prep&&due.daysLeft<=60)return{level:due.daysLeft<=30?'Urgente':'Prossima',title:'Prepariamoci alla nascita',message:prep.title,details:[`Categoria: ${prep.category}`,'Completa una piccola attività alla volta'],time:'circa 10 minuti',view:'preparazione'};
 }
 const docs=(state.documents||[]).filter(d=>d.status==='Manca'||(!d.status&&!d.done));
 if(docs.length)return{level:'Priorità',title:'Completiamo un documento importante',message:`Risultano ${docs.length} documenti ancora mancanti. Iniziamo da “${docs[0].name}”.`,details:['⬜ Verifica cosa manca','⬜ Aggiorna lo stato del documento'],time:'circa 5 minuti',view:'documenti'};
 if(state.profile?.mode==='pregnancy'){
  const info=pregnancyInfo(state.profile.birthDate),latest=[...(state.pregnancyNotes||[])].sort((a,b)=>(b.date||'').localeCompare(a.date||''))[0];
  if(!latest||Number(latest.week)!==Number(info.week))return{level:'Questa settimana',title:`Conserviamo un ricordo della ${info.week}ª settimana`,message:'Aggiorna il diario con come state, un momento da ricordare e le domande per il prossimo controllo.',details:['⬜ Come sta la mamma','⬜ Come sta il papà','⬜ Domande per il medico'],time:'circa 5 minuti',view:'diario'};
 }
 const next=nextJourneyItem();if(next)return{level:'Prossimo passo',title:next.title,message:next.description,details:[`⬜ ${next.group}`,`Periodo: ${next.meta}`],time:'circa 5 minuti',view:next.group==='Diario'?'diario':'checklist',itemId:next.id};
 return{level:'Tutto in ordine',title:'Avete completato le priorità disponibili',message:'Potete controllare il calendario oppure aggiungere un ricordo al diario.',details:['✔ Nessuna urgenza rilevata'],time:'quando volete',view:'calendario'};
}
function renderTodayAssistant(){const box=$('todayAssistant');if(!box)return;const p=getTodayPriority();$('todayAssistantTitle').textContent=p.title;$('todayAssistantMessage').textContent=p.message;$('todayAssistantDetails').innerHTML=(p.details||[]).map(x=>`<div>${esc(x)}</div>`).join('');$('todayAssistantTime').textContent=`Tempo richiesto: ${p.time}`;$('todayPriorityBadge').textContent=p.level;$('todayPriorityBadge').className='badge '+(p.level==='Urgente'?'urgent':p.level==='Prossima'?'soon':'');$('todayAssistantAction').onclick=()=>showView(p.view)}
function renderDashboard(){
const today=new Date().toISOString().slice(0,10),future=[...state.deadlines].filter(x=>x.date>=today).sort((a,b)=>a.date.localeCompare(b.date));
$('metricCompleted').textContent=state.completed.length;
$('metricAppointments').textContent=future.length;
$('metricDocuments').textContent=state.documents.length;
$('metricBenefits').textContent=state.benefits.filter(x=>x.status==='Approvata').length;
const dashboardItems=activeItems();const pending=dashboardItems.filter(x=>!state.completed.includes(x.id)).slice(0,4);
$('todayList').innerHTML=pending.length?pending.map((x,i)=>`<div class="compact-item ${i===0?'is-urgent':i===1?'is-soon':''}"><input type="checkbox" data-check="${x.id}" aria-label="Completa ${esc(x.title)}"><div class="grow"><strong>${esc(x.title)}</strong><br><small>${esc(x.group)} · ${esc(x.meta)}</small></div><span class="badge ${i===0?'urgent':i===1?'soon':''}">${i===0?'Priorità':i===1?'Prossima':'Da fare'}</span></div>`).join(''):'<div class="empty-state">Hai completato tutte le attività della checklist.</div>';
const upcoming=future.slice(0,3);
$('nextAppointments').innerHTML=upcoming.length?upcoming.map(x=>{const d=new Date(x.date+'T00:00:00');return`<div class="compact-item"><div class="date-box"><strong>${d.getDate()}</strong>${d.toLocaleDateString('it-IT',{month:'short'}).toUpperCase()}</div><div class="grow"><strong>${esc(x.title)}</strong><br><small>${esc(x.category||'Appuntamento')} ${esc(x.time||'')}</small></div></div>`}).join(''):'<div class="empty-state">Nessun appuntamento futuro.</div>';
const groups=[...new Set(dashboardItems.map(x=>x.group))].slice(0,4);
$('progressList').innerHTML=groups.map(g=>{const all=dashboardItems.filter(x=>x.group===g),done=all.filter(x=>state.completed.includes(x.id)).length,pct=Math.round(done/all.length*100);return`<div class="progress-block"><div class="progress-label"><span>${esc(g)}</span><span>${done}/${all.length}</span></div><div class="progress-track" aria-label="${esc(g)} ${pct}%"><div class="progress-bar" style="width:${pct}%"></div></div></div>`}).join('');
$('recentDocs').innerHTML=state.documents.slice(-4).reverse().map(x=>`<div class="doc-chip"><div class="doc-icon">📄</div><strong>${esc(x.name)}</strong><br><small>${esc(x.category||'Documento')}</small></div>`).join('')||'<div class="empty-state">Nessun documento.</div>';
renderTodayAssistant();
document.querySelectorAll('[data-check]').forEach(c=>c.onchange=()=>toggleCompleted(c.dataset.check))}
function toggleCompleted(id){state.completed=state.completed.includes(id)?state.completed.filter(x=>x!==id):[...state.completed,id];persist()}
function renderJourney(){const f=$('phaseFilter').value;const source=allJourneyItems();$('journeyList').innerHTML=source.filter(x=>f==='all'||x.phase===f).map(x=>`<article class="data-card ${state.completed.includes(x.id)?'completed':''}"><div class="check-row"><input type="checkbox" data-journey="${x.id}" ${state.completed.includes(x.id)?'checked':''}><div class="card-main"><h3>${esc(x.title)}</h3><small>${esc(x.group)} · ${esc(x.meta)}</small><p>${esc(x.description)}</p></div></div></article>`).join('');document.querySelectorAll('[data-journey]').forEach(c=>c.onchange=()=>toggleCompleted(c.dataset.journey))}
function renderVisits(){
const entries=[...(state.visits||[])].sort((a,b)=>(a.date||'').localeCompare(b.date||''));
$('visitList').innerHTML=entries.map(x=>`<article class="visit-card"><div class="visit-date"><strong>${new Date(x.date+'T00:00:00').getDate()}</strong><small>${new Date(x.date+'T00:00:00').toLocaleDateString('it-IT',{month:'short'}).toUpperCase()}</small></div><div class="card-main"><div class="visit-head"><div><h3>${esc(x.title)}</h3><small>${esc(x.time||'Orario da definire')} · ${esc(x.specialist||'Specialista non indicato')}</small></div><span class="badge">${x.outcome?'Completata':'Da preparare'}</span></div>${x.place?`<p><strong>Struttura:</strong> ${esc(x.place)}</p>`:''}${x.documents?`<div class="visit-box"><strong>📄 Documenti da portare</strong><p>${esc(x.documents)}</p></div>`:''}${x.questions?`<div class="visit-box questions"><strong>❓ Domande da fare</strong><p>${esc(x.questions)}</p></div>`:''}${x.outcome?`<div class="visit-box outcome"><strong>✅ Note dopo la visita</strong><p>${esc(x.outcome)}</p></div>`:''}</div><div class="card-actions"><button data-visit-edit="${x.id}" title="Aggiorna note">✏️</button><button data-visit-del="${x.id}" title="Elimina">🗑️</button></div></article>`).join('')||'<div class="empty-state">Nessuna visita ancora salvata.</div>';
document.querySelectorAll('[data-visit-del]').forEach(b=>b.onclick=()=>{const id=b.dataset.visitDel;state.visits=(state.visits||[]).filter(x=>x.id!==id);persist()});
document.querySelectorAll('[data-visit-edit]').forEach(b=>b.onclick=()=>{const x=(state.visits||[]).find(v=>v.id===b.dataset.visitEdit);if(!x)return;const note=prompt('Aggiorna le note dopo la visita:',x.outcome||'');if(note!==null){x.outcome=note.trim();persist()}})
}
function renderDeadlines(){$('deadlineList').innerHTML=[...state.deadlines].sort((a,b)=>a.date.localeCompare(b.date)).map(x=>`<article class="data-card"><div class="date-box"><strong>${new Date(x.date+'T00:00:00').getDate()}</strong>${new Date(x.date+'T00:00:00').toLocaleDateString('it-IT',{month:'short'}).toUpperCase()}</div><div class="card-main"><h3>${esc(x.title)}</h3><small>${esc(x.category)} · ${esc(x.time||'Orario non indicato')}</small><p>${esc(x.notes||'')}</p></div><div class="card-actions"><button data-del-deadline="${x.id}">🗑️</button></div></article>`).join('')||'<p>Nessuna scadenza salvata.</p>';document.querySelectorAll('[data-del-deadline]').forEach(b=>b.onclick=()=>{state.deadlines=state.deadlines.filter(x=>x.id!==b.dataset.delDeadline);persist()})}
function renderDocuments(){
const docs=state.documents||[],complete=docs.filter(x=>x.status==='Completo'||x.done).length,missing=docs.filter(x=>x.status==='Manca'||(!x.status&&!x.done)).length,expiring=docs.filter(x=>x.expiry&&new Date(x.expiry+'T23:59:59')>=new Date()&&new Date(x.expiry+'T23:59:59')-new Date()<=30*86400000).length;
$('documentSummary').innerHTML=`<div class="doc-stat"><strong>${complete}</strong><small>completi</small></div><div class="doc-stat warning"><strong>${missing}</strong><small>mancanti</small></div><div class="doc-stat alert"><strong>${expiring}</strong><small>in scadenza</small></div>`;
const sorted=[...docs].sort((a,b)=>{const rank=x=>x.status==='Manca'?0:x.status==='Da aggiornare'?1:2;return rank(a)-rank(b)||(a.expiry||'9999').localeCompare(b.expiry||'9999')});
$('documentList').innerHTML=sorted.map(x=>{const visit=(state.visits||[]).find(v=>v.id===x.visitId);const status=x.status||(x.done?'Completo':'Manca');return `<article class="document-card ${status==='Completo'?'completed':''}"><div class="doc-icon">📄</div><div class="card-main"><div class="document-head"><div><h3>${esc(x.name)}</h3><small>${esc(x.category||'Documento')}</small></div><span class="badge doc-${status.toLowerCase().replaceAll(' ','-')}">${esc(status)}</span></div>${x.date?`<p><strong>Data documento:</strong> ${fmtDate(x.date)}</p>`:''}${x.expiry?`<p><strong>Scadenza:</strong> ${fmtDate(x.expiry)}</p>`:''}${visit?`<p><strong>Collegato a:</strong> ${esc(visit.title)} · ${fmtDate(visit.date)}</p>`:''}${x.notes?`<div class="document-notes">${esc(x.notes)}</div>`:''}</div><div class="card-actions"><button data-doc-edit="${x.id}" title="Modifica">✏️</button><button data-doc-toggle="${x.id}" title="Cambia stato">${status==='Completo'?'↩️':'✅'}</button><button data-doc-del="${x.id}" title="Elimina">🗑️</button></div></article>`}).join('')||'<div class="empty-state">Nessun documento registrato.</div>';
document.querySelectorAll('[data-doc-toggle]').forEach(b=>b.onclick=()=>{const x=state.documents.find(d=>d.id===b.dataset.docToggle);x.status=(x.status==='Completo'?'Manca':'Completo');x.done=x.status==='Completo';persist()});
document.querySelectorAll('[data-doc-del]').forEach(b=>b.onclick=()=>{state.documents=state.documents.filter(x=>x.id!==b.dataset.docDel);persist()});
document.querySelectorAll('[data-doc-edit]').forEach(b=>b.onclick=()=>{const x=state.documents.find(d=>d.id===b.dataset.docEdit);if(!x)return;$('documentId').value=x.id;$('documentName').value=x.name;$('documentCategory').value=x.category||'Altro';$('documentStatus').value=x.status||'Manca';$('documentDate').value=x.date||'';$('documentExpiry').value=x.expiry||'';$('documentVisit').value=x.visitId||'';$('documentNotes').value=x.notes||'';$('documentSubmit').textContent='Salva modifiche';window.scrollTo({top:0,behavior:'smooth'})});
const select=$('documentVisit');if(select){const current=select.value;select.innerHTML='<option value="">Nessuna visita collegata</option>'+(state.visits||[]).map(v=>`<option value="${v.id}">${esc(v.title)} · ${fmtDate(v.date)}</option>`).join('');select.value=current}
}

function renderSimpleList(target,arr,key){$(target).innerHTML=arr.map(x=>`<article class="data-card"><div class="doc-icon">${key==='health'?'❤️':'🎓'}</div><div class="card-main"><h3>${esc(x.title)}</h3><small>${esc(x.type||x.year||'')}</small><p>${esc(x.notes||'')}</p></div><div class="card-actions"><button data-simple-del="${key}|${x.id}">🗑️</button></div></article>`).join('')||'<p>Nessun elemento inserito.</p>';document.querySelectorAll('[data-simple-del]').forEach(b=>b.onclick=()=>{const [k,id]=b.dataset.simpleDel.split('|');state[k]=state[k].filter(x=>x.id!==id);persist()})}
function renderBenefits(){$('benefitsList').innerHTML=state.benefits.map(x=>`<article class="data-card"><div class="doc-icon">🎁</div><div class="card-main"><h3>${esc(x.title)}</h3><span class="badge">${esc(x.status)}</span><p>${esc(x.notes||'')}</p></div><select data-benefit="${x.id}"><option ${x.status==='Da verificare'?'selected':''}>Da verificare</option><option ${x.status==='Da richiedere'?'selected':''}>Da richiedere</option><option ${x.status==='Richiesta inviata'?'selected':''}>Richiesta inviata</option><option ${x.status==='Approvata'?'selected':''}>Approvata</option></select></article>`).join('');document.querySelectorAll('[data-benefit]').forEach(s=>s.onchange=()=>{state.benefits.find(x=>x.id===s.dataset.benefit).status=s.value;persist()})}
function renderExpenses(){const total=state.expenses.reduce((a,x)=>a+Number(x.amount||0),0);$('expenseTotal').textContent=total.toLocaleString('it-IT',{style:'currency',currency:'EUR'});$('expenseList').innerHTML=[...state.expenses].sort((a,b)=>b.date.localeCompare(a.date)).map(x=>`<article class="data-card"><div class="doc-icon">💶</div><div class="card-main"><h3>${esc(x.title)}</h3><small>${fmtDate(x.date)} · ${esc(x.category)}</small></div><strong>${Number(x.amount).toLocaleString('it-IT',{style:'currency',currency:'EUR'})}</strong><div class="card-actions"><button data-exp-del="${x.id}">🗑️</button></div></article>`).join('')||'<p>Nessuna spesa registrata.</p>';document.querySelectorAll('[data-exp-del]').forEach(b=>b.onclick=()=>{state.expenses=state.expenses.filter(x=>x.id!==b.dataset.expDel);persist()})}
function birthPrepAvailable(item){if(state.profile?.mode!=='pregnancy')return true;return pregnancyInfo(state.profile.birthDate).daysLeft<=Number(item.daysBefore||999)}
function renderBirthPrep(){
 const section=$('preparazione');if(!section)return;
 const isPreg=state.profile?.mode==='pregnancy';$('birthPrepIntro').textContent=isPreg?`Mancano circa ${pregnancyInfo(state.profile.birthDate).daysLeft} giorni alla data presunta del parto. Le attività vengono proposte al momento giusto.`:'Una checklist personalizzabile per organizzare il rientro e le prime settimane.';
 state.birthPrep=state.birthPrep||defaultBirthPrep.map(x=>({...x,done:false,custom:false,notes:''}));
 const filter=$('birthPrepFilter')?.value||'all';const items=state.birthPrep.filter(x=>filter==='all'||x.category===filter);
 const available=items.filter(birthPrepAvailable),later=items.filter(x=>!birthPrepAvailable(x));
 const renderItem=x=>`<article class="prep-card ${x.done?'completed':''}"><label class="prep-check"><input type="checkbox" data-prep-check="${x.id}" ${x.done?'checked':''}><span></span></label><div class="card-main"><div class="prep-head"><h3>${esc(x.title)}</h3><span class="badge ${x.priority==='Alta'?'urgent':''}">${esc(x.category)}</span></div><small>${x.custom?'Attività personalizzata':`Consigliata entro ${x.daysBefore} giorni dal parto`}</small>${x.notes?`<p>${esc(x.notes)}</p>`:''}</div><button class="icon-btn" data-prep-del="${x.id}" aria-label="Elimina">🗑️</button></article>`;
 $('birthPrepList').innerHTML=available.map(renderItem).join('')||'<div class="empty-state">Nessuna attività in questa categoria.</div>';
 $('birthPrepLater').innerHTML=later.length?`<details class="panel"><summary>Attività che compariranno più avanti (${later.length})</summary><div class="prep-list later-list">${later.map(renderItem).join('')}</div></details>`:'';
 const done=state.birthPrep.filter(x=>x.done).length,total=state.birthPrep.length,pct=total?Math.round(done/total*100):0;$('birthPrepProgress').style.width=pct+'%';$('birthPrepProgressText').textContent=`${done} di ${total} attività completate · ${pct}%`;
 document.querySelectorAll('[data-prep-check]').forEach(c=>c.onchange=()=>{const x=state.birthPrep.find(i=>i.id===c.dataset.prepCheck);if(x){x.done=c.checked;persist()}});
 document.querySelectorAll('[data-prep-del]').forEach(b=>b.onclick=()=>{const x=state.birthPrep.find(i=>i.id===b.dataset.prepDel);if(!x?.custom&&!confirm('Eliminare questa attività dalla checklist?'))return;state.birthPrep=state.birthPrep.filter(i=>i.id!==b.dataset.prepDel);persist()});
}
function renderDiary(){$('diaryList').innerHTML=[...state.diary].sort((a,b)=>b.date.localeCompare(a.date)).map(x=>`<article class="data-card"><div class="doc-icon">⭐</div><div class="card-main"><h3>${esc(x.title)}</h3><small>${fmtDate(x.date)}</small><p>${esc(x.text)}</p></div><div class="card-actions"><button data-dia-del="${x.id}">🗑️</button></div></article>`).join('')||'<p>Il diario è ancora vuoto.</p>';document.querySelectorAll('[data-dia-del]').forEach(b=>b.onclick=()=>{state.diary=state.diary.filter(x=>x.id!==b.dataset.diaDel);persist()})}
function renderPregnancyDiary(){
const preg=state.profile?.mode==='pregnancy',box=$('pregnancyDiaryBox'),standard=$('standardDiaryBox');if(!box||!standard)return;
box.classList.toggle('hidden',!preg);standard.classList.toggle('hidden',preg);$('diarySubtitle').textContent=preg?'La storia dell’attesa, settimana dopo settimana.':'Traguardi, ricordi e progressi.';if(!preg)return;
const info=pregnancyInfo(state.profile.birthDate);$('diaryWeekTitle').textContent=`${info.week}ª settimana di gravidanza`;
if(!$('pregDiaryDate').value)$('pregDiaryDate').value=new Date().toISOString().slice(0,10);if(!$('pregDiaryWeek').value)$('pregDiaryWeek').value=info.week;
const entries=[...(state.pregnancyNotes||[])].sort((a,b)=>(b.date||'').localeCompare(a.date||''));
$('pregnancyDiaryList').innerHTML=entries.map(x=>`<article class="weekly-diary-card"><div class="week-badge"><strong>${esc(x.week)}</strong><small>settimana</small></div><div class="card-main"><div class="weekly-head"><h3>${fmtDate(x.date)}</h3><button data-preg-dia-del="${x.id}" aria-label="Elimina">🗑️</button></div><div class="mood-row"><span>🤰 ${esc(x.motherMood||'—')}</span><span>👨 ${esc(x.fatherMood||'—')}</span></div><p class="memory-text">${esc(x.memory)}</p>${x.questions?`<div class="doctor-questions"><strong>Domande per il medico</strong><p>${esc(x.questions)}</p></div>`:''}</div></article>`).join('')||'<div class="empty-state">Nessun ricordo ancora salvato. Iniziate dalla settimana che state vivendo.</div>';
document.querySelectorAll('[data-preg-dia-del]').forEach(b=>b.onclick=()=>{state.pregnancyNotes=(state.pregnancyNotes||[]).filter(x=>x.id!==b.dataset.pregDiaDel);persist()})}
$('profileForm').onsubmit=e=>{e.preventDefault();state.profile={childName:$('childName').value.trim(),mode:$('journeyMode').value,familyCode:$('familyCode').value.trim().toUpperCase(),birthDate:$('birthDate').value};persist(false);renderAll();syncToGoogle(false)};
document.querySelectorAll('[data-view]').forEach(b=>b.onclick=()=>showView(b.dataset.view));document.querySelectorAll('[data-view-target]').forEach(b=>b.onclick=()=>showView(b.dataset.viewTarget));$('menuBtn').onclick=()=>$('sidebar').classList.toggle('open');$('phaseFilter').onchange=renderJourney;$('syncBtn').onclick=()=>syncToGoogle(true);$('bottomSync').onclick=()=>syncToGoogle(true);$('reloadBtn').onclick=()=>loadFromGoogle(true);
$('visitForm').onsubmit=e=>{e.preventDefault();const visit={id:uid(),title:$('visitTitle').value.trim(),date:$('visitDate').value,time:$('visitTime').value,specialist:$('visitSpecialist').value.trim(),place:$('visitPlace').value.trim(),documents:$('visitDocuments').value.trim(),questions:$('visitQuestions').value.trim(),outcome:$('visitOutcome').value.trim()};state.visits=state.visits||[];state.visits.push(visit);if($('visitAddCalendar').checked){state.deadlines.push({id:'visit-'+visit.id,title:visit.title,date:visit.date,time:visit.time,category:'Salute',notes:[visit.specialist,visit.place].filter(Boolean).join(' · ')})}e.target.reset();$('visitAddCalendar').checked=true;persist()};
$('deadlineForm').onsubmit=e=>{e.preventDefault();state.deadlines.push({id:uid(),title:$('deadlineTitle').value.trim(),date:$('deadlineDate').value,time:$('deadlineTime').value,category:$('deadlineCategory').value,notes:$('deadlineNotes').value.trim()});e.target.reset();persist()};
$('documentForm').onsubmit=e=>{e.preventDefault();const id=$('documentId').value||uid();const item={id,name:$('documentName').value.trim(),category:$('documentCategory').value,status:$('documentStatus').value,done:$('documentStatus').value==='Completo',date:$('documentDate').value,expiry:$('documentExpiry').value,visitId:$('documentVisit').value,notes:$('documentNotes').value.trim()};const idx=state.documents.findIndex(x=>x.id===id);if(idx>=0)state.documents[idx]=item;else state.documents.push(item);e.target.reset();$('documentId').value='';$('documentSubmit').textContent='Aggiungi documento';persist()};
$('healthForm').onsubmit=e=>{e.preventDefault();state.health.push({id:uid(),title:$('healthTitle').value.trim(),type:$('healthType').value,notes:$('healthNotes').value.trim()});e.target.reset();persist()};
$('schoolForm').onsubmit=e=>{e.preventDefault();state.school.push({id:uid(),title:$('schoolTitle').value.trim(),year:$('schoolYear').value.trim(),notes:$('schoolNotes').value.trim()});e.target.reset();persist()};
$('expenseForm').onsubmit=e=>{e.preventDefault();state.expenses.push({id:uid(),title:$('expenseTitle').value.trim(),amount:Number($('expenseAmount').value),date:$('expenseDate').value,category:$('expenseCategory').value});e.target.reset();persist()};
$('diaryForm').onsubmit=e=>{e.preventDefault();state.diary.push({id:uid(),title:$('diaryTitle').value.trim(),date:$('diaryDate').value,text:$('diaryText').value.trim()});e.target.reset();persist()};
$('pregnancyDiaryForm').onsubmit=e=>{e.preventDefault();state.pregnancyNotes=state.pregnancyNotes||[];state.pregnancyNotes.push({id:uid(),date:$('pregDiaryDate').value,week:Number($('pregDiaryWeek').value),motherMood:$('pregDiaryMother').value,fatherMood:$('pregDiaryFather').value,memory:$('pregDiaryMemory').value.trim(),questions:$('pregDiaryQuestions').value.trim()});e.target.reset();$('pregDiaryDate').value=new Date().toISOString().slice(0,10);$('pregDiaryWeek').value=pregnancyInfo(state.profile.birthDate).week;persist();};
$('birthPrepForm').onsubmit=e=>{e.preventDefault();state.birthPrep=state.birthPrep||[];state.birthPrep.push({id:uid(),category:$('birthPrepCategory').value,title:$('birthPrepTitle').value.trim(),daysBefore:Number($('birthPrepDays').value||999),priority:$('birthPrepPriority').value,done:false,custom:true,notes:$('birthPrepNotes').value.trim()});e.target.reset();$('birthPrepDays').value='30';persist()};
$('birthPrepFilter').onchange=renderBirthPrep;
$('editProfileBtn').onclick=()=>{if(!state.profile)return;$('childName').value=state.profile.childName;$('familyCode').value=state.profile.familyCode;$('birthDate').value=state.profile.birthDate;$('journeyMode').value=state.profile.mode||'born';updateDateLabel();$('app').classList.add('hidden');$('onboarding').classList.remove('hidden')};$('resetBtn').onclick=()=>{if(confirm('Cancellare tutti i dati salvati su questo dispositivo?')){localStorage.removeItem('pdp_state');location.reload()}};
window.addEventListener('beforeinstallprompt',e=>{e.preventDefault();deferredPrompt=e;$('installBtn').classList.remove('hidden')});$('installBtn').onclick=async()=>{if(deferredPrompt){deferredPrompt.prompt();await deferredPrompt.userChoice;deferredPrompt=null}};
const APP_VERSION='2.5';let waitingWorker=null;let refreshing=false;
function showUpdate(worker){waitingWorker=worker;$('updateBanner')?.classList.remove('hidden')}
async function registerUpdater(){
  if(!('serviceWorker'in navigator))return;
  try{
    const registration=await navigator.serviceWorker.register('service-worker.js',{updateViaCache:'none'});
    if(registration.waiting&&navigator.serviceWorker.controller)showUpdate(registration.waiting);
    registration.addEventListener('updatefound',()=>{
      const worker=registration.installing;if(!worker)return;
      worker.addEventListener('statechange',()=>{if(worker.state==='installed'&&navigator.serviceWorker.controller)showUpdate(worker)});
    });
    $('checkUpdateBtn').onclick=async()=>{const btn=$('checkUpdateBtn');btn.disabled=true;btn.textContent='Controllo…';try{await registration.update();if(!registration.waiting)btn.textContent='App aggiornata'}catch(e){btn.textContent='Controllo non riuscito'}setTimeout(()=>{btn.disabled=false;btn.textContent='Controlla aggiornamenti'},1800)};
    setInterval(()=>registration.update().catch(()=>{}),60*60*1000);
  }catch(e){console.warn('Aggiornamento PWA non disponibile',e)}
}
$('appVersion').textContent=APP_VERSION;
$('applyUpdateBtn').onclick=()=>{if(waitingWorker){$('applyUpdateBtn').disabled=true;$('applyUpdateBtn').textContent='Aggiornamento…';waitingWorker.postMessage({type:'SKIP_WAITING'})}};
$('updateLaterBtn').onclick=()=>$('updateBanner').classList.add('hidden');
navigator.serviceWorker?.addEventListener('controllerchange',()=>{if(refreshing)return;refreshing=true;location.reload()});
window.addEventListener('load',registerUpdater);
window.addEventListener('online',()=>syncToGoogle(false));window.addEventListener('offline',()=>setSyncStatus('Offline: copia locale','error'));
function updateDateLabel(){const preg=$('journeyMode').value==='pregnancy';$('birthDateLabel').childNodes[0].nodeValue=preg?'Data presunta del parto':'Data di nascita'}$('journeyMode').onchange=updateDateLabel;updateDateLabel();
renderAll();if(state.profile){setSyncStatus(apiConfigured()?'Google collegato':'Configura Apps Script',apiConfigured()?'ok':'error');loadFromGoogle(false)}
