const $=id=>document.getElementById(id);const API_URL=(window.APP_CONFIG?.apiUrl||'').trim();const apiConfigured=()=>API_URL&&!API_URL.includes('INCOLLA_QUI');
const defaultBirthPrep=[
{id:'prep-doc-id',category:'Documenti',title:'Controllare documenti di identità e tessera sanitaria',daysBefore:90,priority:'Alta'},
{id:'prep-folder',category:'Documenti',title:'Preparare la cartella con esami, ecografie e referti',daysBefore:60,priority:'Alta'},
{id:'prep-hospital-info',category:'Ospedale',title:'Verificare indicazioni e lista richiesta dal punto nascita',daysBefore:75,priority:'Alta'},
{id:'prep-mother-bag',category:'Valigia mamma',title:'Preparare cambi, igiene personale e documenti della mamma',daysBefore:45,priority:'Alta'},
{id:'prep-baby-bag',category:'Valigia bambino',title:'Preparare body, tutine, cappellino e copertina',daysBefore:45,priority:'Alta'},
{id:'prep-companion-bag',category:'Accompagnatore',title:'Preparare cambio, caricabatterie, acqua e piccoli snack',daysBefore:30,priority:'Media'},
{id:'prep-car-seat',category:'Casa e rientro',title:'Installare e controllare il seggiolino auto',daysBefore:30,priority:'Alta'},
{id:'prep-sleep',category:'Casa e rientro',title:'Preparare uno spazio sicuro per il sonno del neonato',daysBefore:30,priority:'Alta'},
{id:'prep-pediatrician',category:'Prime settimane',title:'Informarsi sulla scelta del pediatra e sui contatti utili',daysBefore:30,priority:'Media'},
{id:'prep-contacts',category:'Organizzazione',title:'Salvare i contatti del reparto e definire chi avvisare',daysBefore:21,priority:'Media'}
];
const defaultDiagnosisSupport=[
{id:'diag-breathe',category:'Primi passi',title:'Prendersi il tempo per accogliere la notizia',description:'Non è necessario capire o decidere tutto subito. Annotate ciò che sentite e affrontate un passo alla volta.',done:false},
{id:'diag-team',category:'Equipe sanitaria',title:'Salvare i contatti dei professionisti che vi seguono',description:'Ginecologo, centro di diagnosi prenatale, pediatra o centro di riferimento.',done:false},
{id:'diag-questions',category:'Domande',title:'Preparare le domande per il prossimo colloquio',description:'Scrivete dubbi, termini non chiari e informazioni che desiderate ricevere.',done:false},
{id:'diag-docs',category:'Documenti',title:'Raccogliere esami, ecografie e referti',description:'Conservate tutto in una cartella unica, cartacea o digitale.',done:false},
{id:'diag-support',category:'Supporto',title:'Individuare una persona o associazione di fiducia',description:'Un confronto con famiglie o professionisti competenti può aiutare a sentirsi meno soli.',done:false},
{id:'diag-family',category:'Famiglia',title:'Decidere insieme come comunicare la notizia',description:'Scegliete tempi, parole e persone con cui condividere ciò che state vivendo.',done:false}
];

const libraryGuides=[
{id:'guide-diagnosi',category:'Primi passi',title:'Dopo la diagnosi: da dove cominciare',minutes:4,stage:'pregnancy',weekMin:1,summary:'Un percorso pratico per raccogliere informazioni, preparare le domande e non affrontare tutto nello stesso giorno.',sections:[['Un passo alla volta','Non è necessario comprendere ogni aspetto immediatamente. Conservate referti e domande in un unico posto e concentratevi sul prossimo colloquio.'],['Domande utili','Chiedete quali controlli sono previsti, chi sarà il riferimento della famiglia e quali documenti conservare.'],['Supporto','Un confronto con professionisti competenti e associazioni riconosciute può aiutare a orientarsi.']],sources:'Istituto Superiore di Sanità; AIPD',updated:'2026-07-28'},
{id:'guide-morfologica',category:'Gravidanza',title:'Prepararsi all’ecografia morfologica',minutes:3,stage:'pregnancy',weekMin:17,weekMax:23,summary:'Come organizzare documenti e domande prima del controllo, seguendo sempre le indicazioni del ginecologo.',sections:[['Prima della visita','Verificate data, luogo, indicazioni della struttura e portate la documentazione richiesta.'],['Cosa annotare','Scrivete farmaci assunti, sintomi, dubbi e domande che desiderate affrontare.'],['Dopo il controllo','Salvate il referto e registrate eventuali indicazioni o appuntamenti successivi.']],sources:'Sistema Nazionale Linee Guida ISS; professionisti che seguono la gravidanza',updated:'2026-07-28'},
{id:'guide-referti',category:'Vita quotidiana',title:'Creare una cartella ordinata di esami e referti',minutes:3,stage:'all',summary:'Un metodo semplice per ritrovare subito documenti, date e indicazioni importanti.',sections:[['Una struttura unica','Dividete i documenti per gravidanza, visite, esami, pratiche e scuola.'],['Nomi chiari','Usate data, tipo di documento e struttura, per esempio “2026-07-28 Ecografia Ospedale”.'],['Una copia sicura','Conservate una copia protetta e aggiornata, rispettando la riservatezza dei dati sanitari.']],sources:'Buone pratiche organizzative; ISS',updated:'2026-07-28'},
{id:'guide-colloquio',category:'Primi passi',title:'Preparare le domande per il prossimo colloquio',minutes:3,stage:'pregnancy',summary:'Una traccia per uscire dalla visita con informazioni più chiare e utilizzabili.',sections:[['Priorità','Scegliete prima le tre domande più importanti.'],['Parole non chiare','Annotate termini o risultati che desiderate farvi spiegare con parole semplici.'],['Prossimo passo','Chiedete chi contattare, quali controlli programmare e quando fissare il successivo appuntamento.']],sources:'Istituto Superiore di Sanità',updated:'2026-07-28'},
{id:'guide-cuore',category:'Salute',title:'Il controllo cardiologico: come prepararsi',minutes:4,stage:'all',summary:'Documenti, informazioni e domande utili da organizzare prima di una valutazione cardiologica.',sections:[['Cosa portare','Portate referti precedenti, elenco dei farmaci e indicazioni ricevute.'],['Cosa annotare','Segnalate eventuali sintomi o osservazioni richieste dal medico.'],['Dopo la visita','Registrate esito, prescrizioni e data del prossimo controllo.']],sources:'ISS; indicazioni del centro pediatrico di riferimento',updated:'2026-07-28'},
{id:'guide-nascita',category:'Primi mesi',title:'Preparare il passaggio dalla gravidanza alla nascita',minutes:4,stage:'pregnancy',weekMin:30,summary:'Come tenere pronti contatti, documenti e informazioni per le prime giornate.',sections:[['Punto nascita','Controllate le indicazioni specifiche della struttura scelta.'],['Documenti','Riunite documenti personali, esami e referti richiesti.'],['Contatti','Salvate reparto, pediatra e persone che vi aiuteranno nei primi giorni.']],sources:'Ministero della Salute; punto nascita scelto',updated:'2026-07-28'},
{id:'guide-prime-visite',category:'Primi mesi',title:'Organizzare le prime visite del bambino',minutes:4,stage:'born',summary:'Una cronologia semplice di appuntamenti, referti e prossimi controlli concordati con il pediatra.',sections:[['Un calendario unico','Registrate data, struttura, specialista e documenti richiesti.'],['Una scheda per visita','Preparate domande prima e indicazioni dopo ogni appuntamento.'],['Riferimento sanitario','Il programma dei controlli deve essere personalizzato dal pediatra e dal centro che segue il bambino.']],sources:'ISS; pediatra e centro di riferimento',updated:'2026-07-28'},
{id:'guide-inps',category:'Agevolazioni',title:'Invalidità civile e Legge 104: preparare i documenti',minutes:5,stage:'born',summary:'Una panoramica organizzativa dei documenti da raccogliere prima di avviare le pratiche.',sections:[['Certificato introduttivo','La procedura di accertamento parte normalmente da un certificato medico introduttivo.'],['Documentazione','Conservate diagnosi, referti e documenti di identità richiesti.'],['Verifica aggiornata','Controllate sempre il servizio INPS e l’assistenza di patronato o professionisti competenti, perché procedure e requisiti possono cambiare.']],sources:'INPS',updated:'2026-07-28'},
{id:'guide-famiglia',category:'Vita quotidiana',title:'Comunicare la notizia a familiari e amici',minutes:3,stage:'all',summary:'Scegliere tempi e parole che rispettino la famiglia e il bambino.',sections:[['Decidete insieme','Stabilite chi informare, quando e con quali dettagli.'],['Date indicazioni concrete','Potete spiegare quale tipo di aiuto o vicinanza vi è utile.'],['Proteggete i vostri tempi','Non siete obbligati a rispondere subito a tutte le domande.']],sources:'AIPD; buone pratiche di supporto familiare',updated:'2026-07-28'},
{id:'guide-miti',category:'Primi passi',title:'Sindrome di Down: parole corrette e false credenze',minutes:4,stage:'all',summary:'Una guida per parlare prima della persona e riconoscere informazioni poco affidabili.',sections:[['Prima la persona','È preferibile parlare di “persona o bambino con sindrome di Down”.'],['Percorsi individuali','Ogni persona ha caratteristiche, bisogni e possibilità proprie.'],['Fonti affidabili','Verificate le informazioni su fonti istituzionali, scientifiche e associazioni riconosciute.']],sources:'Istituto Superiore di Sanità; AIPD',updated:'2026-07-28'}
];
function suggestedGuide(){const preg=state.profile?.mode==='pregnancy';const week=preg?pregnancyInfo(state.profile.birthDate).week:0;return libraryGuides.find(g=>g.stage===(preg?'pregnancy':'born')&&(!g.weekMin||week>=g.weekMin)&&(!g.weekMax||week<=g.weekMax)&&!(state.readGuides||[]).includes(g.id))||libraryGuides.find(g=>g.stage==='all'&&!(state.readGuides||[]).includes(g.id))||libraryGuides[0]}
function renderRecommendedGuide(){const box=$('recommendedGuide');if(!box)return;const g=suggestedGuide();$('recommendedGuideTitle').textContent=g.title;$('recommendedGuideText').textContent=`${g.summary} · ${g.minutes} min di lettura`;$('recommendedGuideBtn').onclick=()=>{showView('biblioteca');setTimeout(()=>openGuide(g.id),100)}}
function openGuide(id){const g=libraryGuides.find(x=>x.id===id);if(!g)return;state.readGuides=state.readGuides||[];if(!state.readGuides.includes(id)){state.readGuides.push(id);persist()}const card=document.querySelector(`[data-guide-card="${id}"]`);if(card){card.classList.add('open');card.scrollIntoView({behavior:'smooth',block:'start'})}}
function renderLibrary(){if(!$('libraryList'))return;state.favoriteGuides=state.favoriteGuides||[];state.readGuides=state.readGuides||[];const q=($('librarySearch')?.value||'').toLowerCase().trim(),cat=$('libraryCategory')?.value||'all',favOnly=$('libraryFavoritesOnly')?.checked;const list=libraryGuides.filter(g=>(cat==='all'||g.category===cat)&&(!favOnly||state.favoriteGuides.includes(g.id))&&(!q||[g.title,g.summary,g.category,...g.sections.flat()].join(' ').toLowerCase().includes(q)));$('libraryStats').innerHTML=`<span><strong>${libraryGuides.length}</strong> guide offline</span><span><strong>${state.favoriteGuides.length}</strong> preferite</span><span><strong>${state.readGuides.length}</strong> lette</span>`;$('libraryList').innerHTML=list.map(g=>`<article class="library-card ${state.readGuides.includes(g.id)?'read':''}" data-guide-card="${g.id}"><div class="library-card-head"><div><span class="section-kicker">${esc(g.category)}</span><h2>${esc(g.title)}</h2></div><button class="favorite-btn ${state.favoriteGuides.includes(g.id)?'active':''}" data-guide-fav="${g.id}" aria-label="Preferito">${state.favoriteGuides.includes(g.id)?'★':'☆'}</button></div><p>${esc(g.summary)}</p><div class="guide-meta"><span>⏱ ${g.minutes} min</span><span>${state.readGuides.includes(g.id)?'✓ Letta':'Da leggere'}</span></div><button class="soft-btn" data-guide-open="${g.id}">Leggi la guida</button><div class="guide-content">${g.sections.map(s=>`<section><h3>${esc(s[0])}</h3><p>${esc(s[1])}</p></section>`).join('')}<div class="guide-source"><strong>Fonti di riferimento:</strong> ${esc(g.sources)}<br><small>Aggiornata il ${fmtDate(g.updated)}</small></div></div></article>`).join('')||'<div class="empty-state">Nessuna guida corrisponde alla ricerca.</div>';document.querySelectorAll('[data-guide-open]').forEach(b=>b.onclick=()=>openGuide(b.dataset.guideOpen));document.querySelectorAll('[data-guide-fav]').forEach(b=>b.onclick=()=>{const id=b.dataset.guideFav;state.favoriteGuides=state.favoriteGuides.includes(id)?state.favoriteGuides.filter(x=>x!==id):[...state.favoriteGuides,id];persist()})}

const pregnancyItems=[
{id:'preg-w12',phase:'gravidanza',week:12,group:'Gravidanza',title:'Raccogliere esami ed ecografie',meta:'Entro la 12ª settimana',description:'Conservare in un unico posto referti, analisi ed ecografie già effettuate.'},
{id:'preg-questions',phase:'gravidanza',week:16,group:'Preparazione visite',title:'Preparare le domande per il ginecologo',meta:'Dalla 16ª settimana',description:'Annotare dubbi, farmaci assunti e domande da portare al prossimo controllo.'},
{id:'preg-morphology',phase:'gravidanza',week:18,group:'Controlli',title:'Programmare la morfologica',meta:'Generalmente tra 19ª e 21ª settimana',description:'Verificare con il ginecologo la data più adatta e le indicazioni personali.'},
{id:'preg-baby-center',phase:'gravidanza',week:20,group:'Organizzazione',title:'Individuare il centro pediatrico di riferimento',meta:'Dal secondo trimestre',description:'Salvare contatti e indicazioni ricevute dai professionisti che seguono la gravidanza.'},
{id:'preg-diary',phase:'gravidanza',week:22,group:'Diario',title:'Scrivere un ricordo della gravidanza',meta:'Quando desiderate',description:'Annotare emozioni, momenti speciali e pensieri da conservare.'},
{id:'preg-documents',phase:'gravidanza',week:28,group:'Documenti',title:'Preparare la cartella per l’ospedale',meta:'Terzo trimestre',description:'Raccogliere documenti personali, esami, ecografie e indicazioni cliniche.'},
{id:'preg-bag',phase:'gravidanza',week:32,group:'Preparazione parto',title:'Preparare la valigia per il parto',meta:'Tra 32ª e 36ª settimana',description:'Preparare quanto richiesto dalla struttura scelta per mamma e neonato.'},
{id:'preg-birth-plan',phase:'gravidanza',week:36,group:'Preparazione parto',title:'Confermare contatti e piano per il parto',meta:'Ultime settimane',description:'Verificare percorso, numeri utili, accompagnatore e modalità di accesso alla struttura.'}
];
const allJourneyItems=()=>state?.profile?.mode==='pregnancy'?[...pregnancyItems,...journeyItems]:journeyItems;
const journeyItems=[
{id:'birth-registration',phase:'nascita',group:'Pratiche',title:'Registrazione, codice fiscale e pediatra',meta:'Primi giorni',description:'Completare registrazione della nascita, tessera sanitaria e scelta del pediatra.'},
{id:'medical-folder',phase:'nascita',group:'Salute',title:'Creare la cartella sanitaria',meta:'Primo mese',description:'Raccogliere diagnosi, dimissioni, esami, visite e prescrizioni.'},
{id:'inps-start',phase:'nascita',group:'Invalidità civile e 104',title:'Avviare invalidità civile e Legge 104',meta:'Dopo la documentazione medica',description:'Preparare certificato introduttivo e domanda INPS.'},
{id:'specialist-checks',phase:'0-3',group:'Salute',title:'Programmare i controlli specialistici',meta:'0–3 anni',description:'Seguire il piano indicato da pediatra e centro di riferimento.'},
{id:'early-intervention',phase:'0-3',group:'Terapie e riabilitazione',title:'Attivare la presa in carico precoce',meta:'0–3 anni',description:'Valutare fisioterapia, logopedia e neuropsicomotricità.'},
{id:'allowances',phase:'0-3',group:'Invalidità civile e 104',title:'Verificare prestazioni economiche',meta:'Dopo i verbali',description:'Controllare indennità, Assegno Unico e contributi locali.'},
{id:'nursery',phase:'0-3',group:'Scuola e PEI',title:'Organizzare nido e assistenza educativa',meta:'Prima dell’inserimento',description:'Verificare servizi, priorità ed eventuale assistenza.'},
{id:'preschool-pei',phase:'3-6',group:'Scuola e PEI',title:'Preparare l’ingresso alla scuola dell’infanzia',meta:'3–6 anni',description:'Consegnare documentazione e partecipare alla definizione del PEI.'},
{id:'school-support',phase:'3-6',group:'Scuola e PEI',title:'Verificare sostegno e assistenza',meta:'Ogni anno scolastico',description:'Controllare ore di sostegno, assistenza, trasporto e ausili.'},
{id:'primary-pei',phase:'6-13',group:'Scuola e PEI',title:'Aggiornare annualmente il PEI',meta:'6–13 anni',description:'Definire obiettivi, autonomie, strumenti e verifiche.'},
{id:'tax-benefits',phase:'6-13',group:'Invalidità civile e 104',title:'Controllare agevolazioni fiscali',meta:'Ogni anno',description:'Verificare detrazioni, IVA agevolata e spese sanitarie.'},
{id:'autonomy',phase:'14-18',group:'Autonomia',title:'Costruire un progetto di autonomia',meta:'14–18 anni',description:'Lavorare su mobilità, denaro, cura personale e vita quotidiana.'},
{id:'orientation',phase:'14-18',group:'Scuola e PEI',title:'Pianificare scuola, formazione e lavoro',meta:'Scuola superiore',description:'Valutare orientamento, PCTO e formazione professionale.'},
{id:'age18',phase:'14-18',group:'Invalidità civile e 104',title:'Preparare il passaggio ai 18 anni',meta:'Tra 17 e 18 anni',description:'Verificare pratiche INPS, continuità sanitaria e tutele.'}
];
const defaultDocuments=['Certificato di nascita','Tessera sanitaria','Verbale invalidità civile','Verbale Legge 104','Referti specialistici','Prescrizioni riabilitative','PEI scolastico'];
const defaultBenefits=['Invalidità civile','Legge 104','Indennità di frequenza','Assegno Unico con disabilità','Permessi lavorativi','Agevolazioni fiscali e IVA'];
const emptyState=()=>({profile:null,completed:[],documents:defaultDocuments.map((name,i)=>({id:'doc-'+i,name,category:'Da classificare',status:'Manca',done:false,date:'',expiry:'',visitId:'',notes:''})),deadlines:[],health:[],school:[],benefits:defaultBenefits.map((title,i)=>({id:'ben-'+i,title,status:'Da verificare',notes:''})),expenses:[],diary:[],pregnancyNotes:[],visits:[],birthPrep:defaultBirthPrep.map(x=>({...x,done:false,custom:false,notes:''})),diagnosisSupport:defaultDiagnosisSupport.map(x=>({...x,notes:''})),favoriteGuides:[],readGuides:[],assistantMessages:[],members:[],activeMemberId:'',preferences:{theme:'system',textSize:'normal',highContrast:false,largeIcons:false},syncMeta:{status:'local',lastSuccess:'',lastAttempt:'',pending:false,retries:0,revision:0,error:''},activityLog:[]});
let state=Object.assign(emptyState(),JSON.parse(localStorage.getItem('pdp_state')||'{}'));state.preferences={...emptyState().preferences,...(state.preferences||{})};state.syncMeta={...emptyState().syncMeta,...(state.syncMeta||{})};state.activityLog=state.activityLog||[];state.members=state.members||[];if(state.profile&&!state.members.length){const id='owner-'+(state.profile.familyCode||'family');state.members=[{id,name:'Genitore',role:'Genitore',permission:'owner'}];state.activeMemberId=id}state.documents=(state.documents||[]).map(d=>({...d,status:d.status||(d.done?'Completo':'Manca'),done:(d.status?d.status==='Completo':!!d.done),expiry:d.expiry||'',visitId:d.visitId||'',notes:d.notes||'',fileName:d.fileName||'',fileType:d.fileType||'',fileSize:d.fileSize||0,extractedText:d.extractedText||'',driveFileId:d.driveFileId||'',driveUrl:d.driveUrl||'',driveUploadedAt:d.driveUploadedAt||''}));let syncTimer=null,deferredPrompt=null;
function activity(action,detail=''){
  state.activityLog=state.activityLog||[];
  const user=window.PDP_CLOUD?.getMember?.();
  state.activityLog.unshift({id:uid(),at:new Date().toISOString(),action,detail,by:user?.name||'Utente'});
  state.activityLog=state.activityLog.slice(0,100);
}
function saveLocal(){localStorage.setItem('pdp_state',JSON.stringify(state))}
function persist(sync=true){
  state.syncMeta={...emptyState().syncMeta,...(state.syncMeta||{})};
  if(sync){state.syncMeta.pending=true;state.syncMeta.status=navigator.onLine?'pending':'offline';state.syncMeta.error=''}
  saveLocal();renderAll();if(!sync)return;
  clearTimeout(syncTimer);syncTimer=setTimeout(()=>performCloudSync(false),700);
}
function snapshot(){return {...state,updatedAt:new Date().toISOString()}}
function formatSyncTime(value){if(!value)return'';try{return new Date(value).toLocaleString('it-IT')}catch{return''}}
function setSyncStatus(text,type=''){
  if($('syncStatus'))$('syncStatus').textContent=text;
  if($('syncDot'))$('syncDot').className='sync-dot '+type;
  if($('syncDetails'))$('syncDetails').textContent=state.syncMeta?.lastSuccess?'Ultima sincronizzazione: '+formatSyncTime(state.syncMeta.lastSuccess):'Nessuna sincronizzazione completata';
}
function refreshSyncUi(){
  const m=state.syncMeta||{};
  if(m.status==='syncing')setSyncStatus('Sincronizzazione…');
  else if(m.status==='ok')setSyncStatus('Sincronizzato','ok');
  else if(m.status==='error')setSyncStatus('Errore di sincronizzazione','error');
  else if(m.status==='offline')setSyncStatus('Offline: salvato sul dispositivo','error');
  else if(m.pending)setSyncStatus('Modifiche da sincronizzare');
  else setSyncStatus('Solo sul dispositivo');
}
async function performCloudSync(show=true,force=false){
  state.syncMeta={...emptyState().syncMeta,...(state.syncMeta||{}),lastAttempt:new Date().toISOString()};
  if(!navigator.onLine){state.syncMeta.status='offline';state.syncMeta.pending=true;saveLocal();refreshSyncUi();return false}
  if(window.PDP_CLOUD?.isReady?.()){
    state.syncMeta.status='syncing';saveLocal();refreshSyncUi();
    try{
      const result=await window.PDP_CLOUD.save(snapshot(),{baseRevision:state.syncMeta.revision||window.PDP_CLOUD.getRevision?.()||0,force});
      state.syncMeta={...state.syncMeta,status:'ok',pending:false,retries:0,error:'',lastSuccess:new Date().toISOString(),revision:result?.revision||window.PDP_CLOUD.getRevision?.()||state.syncMeta.revision};
      activity('Sincronizzazione completata','Dati salvati nel cloud');saveLocal();renderActivityLog();refreshSyncUi();
      if(show)alert('Sincronizzazione completata.');return true;
    }catch(e){
      if(e.code==='pdp/conflict'){
        state.syncMeta.status='conflict';state.syncMeta.pending=true;state.syncMeta.error=e.message;saveLocal();
        const useRemote=confirm('Un altro dispositivo ha salvato modifiche più recenti.\n\nOK: scarica la versione cloud.\nAnnulla: conserva questa versione e riprova manualmente.');
        if(useRemote){await window.PDP_CLOUD.reload();state.syncMeta={...state.syncMeta,status:'ok',pending:false,error:'',lastSuccess:new Date().toISOString(),revision:window.PDP_CLOUD.getRevision?.()||0};saveLocal();refreshSyncUi();}
        else{setSyncStatus('Conflitto da risolvere','error')}
        return false;
      }
      state.syncMeta.status='error';state.syncMeta.pending=true;state.syncMeta.retries=(state.syncMeta.retries||0)+1;state.syncMeta.error=e.message||String(e);saveLocal();refreshSyncUi();
      if(show)alert('Dati conservati sul dispositivo. Sincronizzazione non riuscita: '+state.syncMeta.error);
      scheduleRetry();return false;
    }
  }
  if(state.profile?.familyCode&&apiConfigured())return syncToLegacyGoogle(show);
  state.syncMeta.status='local';saveLocal();refreshSyncUi();return false;
}
let retryTimer=null;
function scheduleRetry(){clearTimeout(retryTimer);const n=Math.min(state.syncMeta?.retries||1,6);retryTimer=setTimeout(()=>performCloudSync(false),Math.min(60000,3000*Math.pow(2,n-1)))}
async function syncToLegacyGoogle(show=true){
  if(!apiConfigured()){state.syncMeta.status='local';saveLocal();refreshSyncUi();return false}
  try{const r=await fetch(API_URL,{method:'POST',headers:{'Content-Type':'text/plain;charset=utf-8'},body:JSON.stringify({action:'save',familyCode:state.profile.familyCode,data:snapshot()})});const j=await r.json();if(!j.ok)throw new Error(j.error||'Errore');state.syncMeta={...state.syncMeta,status:'ok',pending:false,lastSuccess:new Date().toISOString(),error:''};saveLocal();refreshSyncUi();return true}catch(e){state.syncMeta.status='error';state.syncMeta.error=e.message;saveLocal();refreshSyncUi();if(show)alert(e.message);return false}
}
async function syncToGoogle(show=true){return performCloudSync(show)}
async function loadFromGoogle(show=true){
  if(window.PDP_CLOUD?.isReady?.()){state.syncMeta.status='syncing';refreshSyncUi();try{await window.PDP_CLOUD.reload();state.syncMeta={...state.syncMeta,status:'ok',pending:false,lastSuccess:new Date().toISOString(),revision:window.PDP_CLOUD.getRevision?.()||0,error:''};saveLocal();refreshSyncUi();if(show)alert('Dati aggiornati dal cloud.')}catch(e){state.syncMeta.status='error';state.syncMeta.error=e.message;saveLocal();refreshSyncUi();if(show)alert(e.message)}return}
  if(!apiConfigured()||!state.profile?.familyCode)return;
}
function ageText(date){if(!date)return'';const b=new Date(date+'T00:00:00'),t=new Date();if(b>t){const d=Math.ceil((b-t)/86400000);return`Nascita prevista tra circa ${d} giorni`}let y=t.getFullYear()-b.getFullYear(),m=t.getMonth()-b.getMonth();if(t.getDate()<b.getDate())m--;if(m<0){y--;m+=12}return y<1?`${Math.max(0,m)} mesi`:`${y} anni e ${Math.max(0,m)} mesi`}
function esc(s){return String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[c]))}
function fmtDate(d){return d?new Date(d+'T00:00:00').toLocaleDateString('it-IT'):'—'}
function uid(){return crypto.randomUUID?crypto.randomUUID():Date.now()+'-'+Math.random()}
function showView(id){document.querySelectorAll('.view').forEach(v=>v.classList.toggle('active-view',v.id===id));document.querySelectorAll('[data-view]').forEach(b=>b.classList.toggle('active',b.dataset.view===id));closeMenu();closeQuickAdd();window.scrollTo({top:0,behavior:'smooth'})}
function renderAll(){if(!state.profile){$('onboarding').classList.remove('hidden');$('app').classList.add('hidden');return}$('onboarding').classList.add('hidden');$('app').classList.remove('hidden');$('profileName').textContent=state.profile.childName;$('profileAge').textContent=state.profile.mode==='pregnancy'?pregnancyLabel(state.profile.birthDate):ageText(state.profile.birthDate);$('profileBirth').textContent=(state.profile.mode==='pregnancy'?'Data presunta del parto: ':'Data di nascita: ')+fmtDate(state.profile.birthDate);$('welcomeText').textContent=state.profile.mode==='pregnancy'?`In attesa di ${state.profile.childName} ❤️`:`Ciao, famiglia di ${state.profile.childName}! 👋`;renderPregnancy();renderJourney();renderTimeline();renderDashboard();renderDeadlines();renderVisits();renderDocuments();renderSimpleList('healthList',state.health,'health');renderSimpleList('schoolList',state.school,'school');renderBenefits();renderExpenses();renderDiary();renderPregnancyDiary();renderBirthPrep();renderDiagnosisSupport();renderLibrary();renderRecommendedGuide();renderAssistant();renderProfessionalNav();renderFamilyMembers();renderActivityLog();refreshSyncUi();applyPreferences();applyMemberPermission();const active=(state.members||[]).find(x=>x.id===state.activeMemberId);if(active&&$('welcomeText'))$('welcomeText').textContent=state.profile.mode==='pregnancy'?`Ciao ${active.name}, in attesa di ${state.profile.childName} ❤️`:`Ciao ${active.name}, famiglia di ${state.profile.childName}! 👋`;$('apiInfo').textContent=window.PDP_CLOUD?.isReady?.()?'Account Firebase collegato. Google Drive resta disponibile per i documenti.':(apiConfigured()?'Google Apps Script configurato.':'Google Apps Script non ancora configurato in config.js.')}
function pregnancyInfo(dueDate){const due=new Date(dueDate+'T00:00:00'),now=new Date();const conception=new Date(due);conception.setDate(conception.getDate()-280);const elapsed=Math.floor((now-conception)/86400000);const week=Math.max(1,Math.min(40,Math.floor(elapsed/7)+1));const daysLeft=Math.max(0,Math.ceil((due-now)/86400000));return{week,daysLeft,pct:Math.max(2,Math.min(100,Math.round(elapsed/280*100)))}}
function pregnancyLabel(date){const i=pregnancyInfo(date);return`${i.week}ª settimana di gravidanza`}
function activeItems(){if(state.profile?.mode!=='pregnancy')return journeyItems;const w=pregnancyInfo(state.profile.birthDate).week;return pregnancyItems.filter(x=>x.week<=w+6)}
function nextJourneyItem(){const items=state.profile?.mode==='pregnancy'?activeItems():journeyItems;return items.find(x=>!state.completed.includes(x.id))||null}
function renderPregnancy(){const box=$('pregnancyHero');if(!box)return;if(state.profile.mode!=='pregnancy'){box.classList.add('hidden');return}box.classList.remove('hidden');const i=pregnancyInfo(state.profile.birthDate),next=nextJourneyItem();$('pregnancyWeek').textContent=`${i.week}ª settimana di gravidanza`;$('pregnancyCountdown').textContent=i.daysLeft?`Mancano circa ${i.daysLeft} giorni alla data presunta del parto.`:'La data presunta del parto è arrivata.';$('pregnancyBar').style.width=i.pct+'%';$('pregnancyProgressText').textContent=`Percorso completato al ${i.pct}% · data presunta ${fmtDate(state.profile.birthDate)}`;$('nextStepTitle').textContent=next?.title||'Avete completato le tappe disponibili';$('nextStepMeta').textContent=next?`${next.meta} · circa 5 minuti`:'Continuate ad aggiornare diario e appuntamenti';$('startNextStep').onclick=()=>showView(next?.group==='Diario'?'diario':'checklist')}
function renderTimeline(){if(!$('journeyTimeline'))return;const isPreg=state.profile.mode==='pregnancy',info=isPreg?pregnancyInfo(state.profile.birthDate):null;const items=isPreg?pregnancyItems:journeyItems;$('journeySubtitle').textContent=isPreg?`Siete alla ${info.week}ª settimana. Le indicazioni sanitarie vanno sempre concordate con i professionisti che seguono la gravidanza.`:'Dalla nascita ai 18 anni, con le vostre tappe.';$('journeyTimeline').innerHTML=items.map(x=>{const done=state.completed.includes(x.id),current=isPreg&&!done&&x.week<=info.week+2&&x.week>=info.week-2;return`<div class="timeline-item ${done?'done':current?'current':''}"><span class="timeline-dot"></span><div class="timeline-card"><h3>${done?'✓ ':''}${esc(x.title)}</h3><small>${esc(x.meta)}</small><p>${esc(x.description)}</p>${!done?`<button class="soft-btn" data-timeline-check="${x.id}">Segna come completato</button>`:''}</div></div>`}).join('');document.querySelectorAll('[data-timeline-check]').forEach(b=>b.onclick=()=>toggleCompleted(b.dataset.timelineCheck))}
function daysBetweenToday(date){const today=new Date();today.setHours(0,0,0,0);const d=new Date(date+'T00:00:00');return Math.ceil((d-today)/86400000)}
function getTodayPriority(){
  if(state.profile?.mode==='pregnancy'){const next=(state.diagnosisSupport||[]).find(x=>!x.done);if(next)return{level:'Prossima',title:'Un passo alla volta',message:next.title,details:[next.category,next.description],time:'circa 5 minuti',view:'diagnosi'};}
 const today=new Date().toISOString().slice(0,10);
 const visits=(state.visits||[]).filter(v=>v.date>=today).sort((a,b)=>a.date.localeCompare(b.date));
 const nextVisit=visits[0];
 if(nextVisit){const days=daysBetweenToday(nextVisit.date);if(days<=7){const missing=[];if(!nextVisit.documents)missing.push('preparare i documenti da portare');if(!nextVisit.questions)missing.push('scrivere le domande da fare');if(missing.length)return{level:days<=2?'Urgente':'Prossima',title:days===0?'La visita è oggi':days===1?'La visita è domani':`Visita tra ${days} giorni`,message:`${nextVisit.title}${nextVisit.specialist?' · '+nextVisit.specialist:''}`,details:missing.map(x=>'⬜ '+x),time:'circa 10 minuti',view:'visite'};return{level:days<=2?'Urgente':'Prossima',title:days===0?'La visita è oggi':days===1?'La visita è domani':`Prepariamo la visita tra ${days} giorni`,message:nextVisit.title,details:['✔ Documenti da portare registrati','✔ Domande già preparate'],time:'circa 5 minuti',view:'visite'}}}
 if(state.profile?.mode==='pregnancy'){
  const due=pregnancyInfo(state.profile.birthDate),prep=(state.birthPrep||[]).find(x=>!x.done&&birthPrepAvailable(x));
  if(prep&&due.daysLeft<=60)return{level:due.daysLeft<=30?'Urgente':'Prossima',title:'Prepariamoci alla nascita',message:prep.title,details:[`Categoria: ${prep.category}`,'Completa una piccola attività alla volta'],time:'circa 10 minuti',view:'preparazione'};
 }
 const docs=(state.documents||[]).filter(d=>d.status==='Manca'||(!d.status&&!d.done));
 if(docs.length)return{level:'Priorità',title:'Completiamo un documento importante',message:`Risultano ${docs.length} documenti ancora mancanti. Iniziamo da “${docs[0].name}”.`,details:['⬜ Verifica cosa manca','⬜ Aggiorna lo stato del documento'],time:'circa 5 minuti',view:'documenti'};
 if(state.profile?.mode==='pregnancy'){
  const info=pregnancyInfo(state.profile.birthDate),latest=[...(state.pregnancyNotes||[])].sort((a,b)=>(b.date||'').localeCompare(a.date||''))[0];
  if(!latest||Number(latest.week)!==Number(info.week))return{level:'Questa settimana',title:`Conserviamo un ricordo della ${info.week}ª settimana`,message:'Aggiorna il diario con come state, un momento da ricordare e le domande per il prossimo controllo.',details:['⬜ Come sta la mamma','⬜ Come sta il papà','⬜ Domande per il medico'],time:'circa 5 minuti',view:'diario'};
 }
 const next=nextJourneyItem();if(next)return{level:'Prossimo passo',title:next.title,message:next.description,details:[`⬜ ${next.group}`,`Periodo: ${next.meta}`],time:'circa 5 minuti',view:next.group==='Diario'?'diario':'checklist',itemId:next.id};
 return{level:'Tutto in ordine',title:'Avete completato le priorità disponibili',message:'Potete controllare il calendario oppure aggiungere un ricordo al diario.',details:['✔ Nessuna urgenza rilevata'],time:'quando volete',view:'calendario'};
}
function renderTodayAssistant(){const box=$('todayAssistant');if(!box)return;const p=getTodayPriority();$('todayAssistantTitle').textContent=p.title;$('todayAssistantMessage').textContent=p.message;$('todayAssistantDetails').innerHTML=(p.details||[]).map(x=>`<div>${esc(x)}</div>`).join('');$('todayAssistantTime').textContent=`Tempo richiesto: ${p.time}`;$('todayPriorityBadge').textContent=p.level;$('todayPriorityBadge').className='badge '+(p.level==='Urgente'?'urgent':p.level==='Prossima'?'soon':'');$('todayAssistantAction').onclick=()=>showView(p.view)}
function renderDashboard(){
const today=new Date().toISOString().slice(0,10),future=[...state.deadlines].filter(x=>x.date>=today).sort((a,b)=>a.date.localeCompare(b.date));
$('metricCompleted').textContent=state.completed.length;
$('metricAppointments').textContent=future.length;
$('metricDocuments').textContent=state.documents.length;
$('metricBenefits').textContent=state.benefits.filter(x=>x.status==='Approvata').length;
const dashboardItems=activeItems();const pending=dashboardItems.filter(x=>!state.completed.includes(x.id)).slice(0,4);
$('todayList').innerHTML=pending.length?pending.map((x,i)=>`<div class="compact-item ${i===0?'is-urgent':i===1?'is-soon':''}"><input type="checkbox" data-check="${x.id}" aria-label="Completa ${esc(x.title)}"><div class="grow"><strong>${esc(x.title)}</strong><br><small>${esc(x.group)} · ${esc(x.meta)}</small></div><span class="badge ${i===0?'urgent':i===1?'soon':''}">${i===0?'Priorità':i===1?'Prossima':'Da fare'}</span></div>`).join(''):'<div class="empty-state">Hai completato tutte le attività della checklist.</div>';
const upcoming=future.slice(0,3);
$('nextAppointments').innerHTML=upcoming.length?upcoming.map(x=>{const d=new Date(x.date+'T00:00:00');return`<div class="compact-item"><div class="date-box"><strong>${d.getDate()}</strong>${d.toLocaleDateString('it-IT',{month:'short'}).toUpperCase()}</div><div class="grow"><strong>${esc(x.title)}</strong><br><small>${esc(x.category||'Appuntamento')} ${esc(x.time||'')}</small></div></div>`}).join(''):'<div class="empty-state">Nessun appuntamento futuro.</div>';
const groups=[...new Set(dashboardItems.map(x=>x.group))].slice(0,4);
$('progressList').innerHTML=groups.map(g=>{const all=dashboardItems.filter(x=>x.group===g),done=all.filter(x=>state.completed.includes(x.id)).length,pct=Math.round(done/all.length*100);return`<div class="progress-block"><div class="progress-label"><span>${esc(g)}</span><span>${done}/${all.length}</span></div><div class="progress-track" aria-label="${esc(g)} ${pct}%"><div class="progress-bar" style="width:${pct}%"></div></div></div>`}).join('');
$('recentDocs').innerHTML=state.documents.slice(-4).reverse().map(x=>`<div class="doc-chip"><div class="doc-icon">📄</div><strong>${esc(x.name)}</strong><br><small>${esc(x.category||'Documento')}</small></div>`).join('')||'<div class="empty-state">Nessun documento.</div>';
renderTodayAssistant();
document.querySelectorAll('[data-check]').forEach(c=>c.onchange=()=>toggleCompleted(c.dataset.check))}
function toggleCompleted(id){state.completed=state.completed.includes(id)?state.completed.filter(x=>x!==id):[...state.completed,id];persist()}
function renderJourney(){const f=$('phaseFilter').value;const source=allJourneyItems();$('journeyList').innerHTML=source.filter(x=>f==='all'||x.phase===f).map(x=>`<article class="data-card ${state.completed.includes(x.id)?'completed':''}"><div class="check-row"><input type="checkbox" data-journey="${x.id}" ${state.completed.includes(x.id)?'checked':''}><div class="card-main"><h3>${esc(x.title)}</h3><small>${esc(x.group)} · ${esc(x.meta)}</small><p>${esc(x.description)}</p></div></div></article>`).join('');document.querySelectorAll('[data-journey]').forEach(c=>c.onchange=()=>toggleCompleted(c.dataset.journey))}
function renderVisits(){
const entries=[...(state.visits||[])].sort((a,b)=>(a.date||'').localeCompare(b.date||''));
$('visitList').innerHTML=entries.map(x=>`<article class="visit-card"><div class="visit-date"><strong>${new Date(x.date+'T00:00:00').getDate()}</strong><small>${new Date(x.date+'T00:00:00').toLocaleDateString('it-IT',{month:'short'}).toUpperCase()}</small></div><div class="card-main"><div class="visit-head"><div><h3>${esc(x.title)}</h3><small>${esc(x.time||'Orario da definire')} · ${esc(x.specialist||'Specialista non indicato')}</small></div><span class="badge">${x.outcome?'Completata':'Da preparare'}</span></div>${x.place?`<p><strong>Struttura:</strong> ${esc(x.place)}</p>`:''}${x.documents?`<div class="visit-box"><strong>📄 Documenti da portare</strong><p>${esc(x.documents)}</p></div>`:''}${x.questions?`<div class="visit-box questions"><strong>❓ Domande da fare</strong><p>${esc(x.questions)}</p></div>`:''}${x.outcome?`<div class="visit-box outcome"><strong>✅ Note dopo la visita</strong><p>${esc(x.outcome)}</p></div>`:''}</div><div class="card-actions"><button data-visit-prepare="${x.id}" title="Prepara visita">✨</button><button data-visit-edit="${x.id}" title="Aggiorna note">✏️</button><button data-visit-del="${x.id}" title="Elimina">🗑️</button></div></article>`).join('')||'<div class="empty-state">Nessuna visita ancora salvata.</div>';
document.querySelectorAll('[data-visit-prepare]').forEach(b=>b.onclick=()=>{showView('assistente');setTimeout(()=>askAssistant('Prepara la visita '+b.dataset.visitPrepare),80)});
document.querySelectorAll('[data-visit-del]').forEach(b=>b.onclick=()=>{const id=b.dataset.visitDel;state.visits=(state.visits||[]).filter(x=>x.id!==id);persist()});
document.querySelectorAll('[data-visit-edit]').forEach(b=>b.onclick=()=>{const x=(state.visits||[]).find(v=>v.id===b.dataset.visitEdit);if(!x)return;const note=prompt('Aggiorna le note dopo la visita:',x.outcome||'');if(note!==null){x.outcome=note.trim();persist()}})
}
function renderDeadlines(){$('deadlineList').innerHTML=[...state.deadlines].sort((a,b)=>a.date.localeCompare(b.date)).map(x=>`<article class="data-card"><div class="date-box"><strong>${new Date(x.date+'T00:00:00').getDate()}</strong>${new Date(x.date+'T00:00:00').toLocaleDateString('it-IT',{month:'short'}).toUpperCase()}</div><div class="card-main"><h3>${esc(x.title)}</h3><small>${esc(x.category)} · ${esc(x.time||'Orario non indicato')}</small><p>${esc(x.notes||'')}</p></div><div class="card-actions"><button data-del-deadline="${x.id}">🗑️</button></div></article>`).join('')||'<p>Nessuna scadenza salvata.</p>';document.querySelectorAll('[data-del-deadline]').forEach(b=>b.onclick=()=>{state.deadlines=state.deadlines.filter(x=>x.id!==b.dataset.delDeadline);persist()})}
const FILE_DB='pdp_document_files_v1',FILE_STORE='files';
function openFileDb(){return new Promise((resolve,reject)=>{const r=indexedDB.open(FILE_DB,1);r.onupgradeneeded=()=>{if(!r.result.objectStoreNames.contains(FILE_STORE))r.result.createObjectStore(FILE_STORE)};r.onsuccess=()=>resolve(r.result);r.onerror=()=>reject(r.error)})}
async function saveDocumentFile(id,file){const db=await openFileDb();return new Promise((resolve,reject)=>{const tx=db.transaction(FILE_STORE,'readwrite');tx.objectStore(FILE_STORE).put(file,id);tx.oncomplete=resolve;tx.onerror=()=>reject(tx.error)})}
async function getDocumentFile(id){const db=await openFileDb();return new Promise((resolve,reject)=>{const r=db.transaction(FILE_STORE).objectStore(FILE_STORE).get(id);r.onsuccess=()=>resolve(r.result||null);r.onerror=()=>reject(r.error)})}
async function deleteDocumentFile(id){const db=await openFileDb();return new Promise((resolve,reject)=>{const tx=db.transaction(FILE_STORE,'readwrite');tx.objectStore(FILE_STORE).delete(id);tx.oncomplete=resolve;tx.onerror=()=>reject(tx.error)})}

const MAX_DRIVE_UPLOAD_BYTES=8*1024*1024;
function fileToBase64(file){return new Promise((resolve,reject)=>{const r=new FileReader();r.onload=()=>resolve(String(r.result).split(',')[1]||'');r.onerror=()=>reject(r.error||new Error('Lettura file non riuscita'));r.readAsDataURL(file)})}
async function uploadDocumentToDrive(id,file,documentName,oldFileId=''){if(!apiConfigured()||!state.profile?.familyCode)throw new Error('Configura Google Apps Script e il codice famiglia prima di caricare il file.');if(file.size>MAX_DRIVE_UPLOAD_BYTES)throw new Error('Il file supera 8 MB. Riduci la dimensione o fotografa una pagina alla volta.');showExtractionProgress('Salvataggio su Google Drive','Caricamento protetto del documento…',25);const base64=await fileToBase64(file);showExtractionProgress('Salvataggio su Google Drive','Invio del file…',65);const r=await fetch(API_URL,{method:'POST',headers:{'Content-Type':'text/plain;charset=utf-8'},body:JSON.stringify({action:'uploadFile',familyCode:state.profile.familyCode,documentId:id,documentName,fileName:file.name,mimeType:file.type||'application/octet-stream',base64,oldFileId})});const j=await r.json();if(!j.ok)throw new Error(j.error||'Caricamento su Drive non riuscito');showExtractionProgress('Salvataggio completato','Il file è stato archiviato su Google Drive.',100);return j}
async function deleteDriveDocument(d){if(!d?.driveFileId||!apiConfigured()||!state.profile?.familyCode)return;try{await fetch(API_URL,{method:'POST',headers:{'Content-Type':'text/plain;charset=utf-8'},body:JSON.stringify({action:'deleteFile',familyCode:state.profile.familyCode,documentId:d.id,fileId:d.driveFileId})})}catch(e){console.warn('Eliminazione Drive non riuscita',e)}}
function formatBytes(n){if(!n)return'';if(n<1024)return n+' B';if(n<1048576)return(n/1024).toFixed(1)+' KB';return(n/1048576).toFixed(1)+' MB'}
async function openStoredFile(id){const d=(state.documents||[]).find(x=>x.id===id),file=await getDocumentFile(id);if(!file){if(d?.driveUrl){window.open(d.driveUrl,'_blank');return}alert('Il file non è disponibile sul dispositivo né su Google Drive.');return}const url=URL.createObjectURL(file);if(file.type.startsWith('image/')){const box=$('documentReader');box.classList.remove('hidden');box.innerHTML=`<div class="reader-head"><div><h3>Anteprima: ${esc(d?.name||file.name)}</h3><p>${esc(file.name)}</p></div><button class="soft-btn" onclick="document.getElementById('documentReader').classList.add('hidden')">Chiudi</button></div><img class="file-preview" src="${url}" alt="Anteprima documento">`;box.scrollIntoView({behavior:'smooth'})}else window.open(url,'_blank');setTimeout(()=>URL.revokeObjectURL(url),60000)}

const OCR_MAX_PDF_PAGES=4;
function showExtractionProgress(title,message,percent=0){const box=$('documentReader');box.classList.remove('hidden');box.innerHTML=`<div class="reader-head"><div><h3>🔎 ${esc(title)}</h3><p>${esc(message)}</p></div></div><div class="extract-progress"><div class="progress-track"><div class="progress-bar" style="width:${Math.max(3,Math.min(100,percent))}%"></div></div><small>${Math.round(percent)}%</small></div><p class="privacy-note">L’estrazione del testo avviene nel browser. Se attivato, il file originale viene archiviato nella cartella privata Google Drive della famiglia.</p>`;box.scrollIntoView({behavior:'smooth',block:'start'})}
async function extractPdfText(file){if(!window.pdfjsLib)throw new Error('Modulo PDF non disponibile. Controlla la connessione e riprova.');pdfjsLib.GlobalWorkerOptions.workerSrc='https://cdnjs.cloudflare.com/ajax/libs/pdf.js/3.11.174/pdf.worker.min.js';const data=await file.arrayBuffer(),pdf=await pdfjsLib.getDocument({data}).promise;let parts=[];for(let i=1;i<=pdf.numPages;i++){showExtractionProgress('Lettura del PDF',`Pagina ${i} di ${pdf.numPages}`,i/pdf.numPages*70);const page=await pdf.getPage(i),content=await page.getTextContent(),text=content.items.map(x=>x.str).join(' ').replace(/\s+/g,' ').trim();if(text)parts.push(text)}let result=parts.join('\n\n').trim();if(result.length>=80)return result;if(!window.Tesseract)throw new Error('Il PDF sembra una scansione. Il modulo OCR non è disponibile.');parts=[];const pages=Math.min(pdf.numPages,OCR_MAX_PDF_PAGES);for(let i=1;i<=pages;i++){const page=await pdf.getPage(i),viewport=page.getViewport({scale:1.6}),canvas=document.createElement('canvas'),ctx=canvas.getContext('2d');canvas.width=viewport.width;canvas.height=viewport.height;await page.render({canvasContext:ctx,viewport}).promise;const r=await Tesseract.recognize(canvas,'ita+eng',{logger:m=>{if(m.status==='recognizing text')showExtractionProgress('Riconoscimento della scansione',`Pagina ${i} di ${pages}`,70+((i-1+m.progress)/pages)*30)}});if(r.data.text.trim())parts.push(r.data.text.trim())}return parts.join('\n\n').trim()}
async function extractImageText(file){if(!window.Tesseract)throw new Error('Modulo OCR non disponibile. Apri l’app con connessione internet e riprova.');const r=await Tesseract.recognize(file,'ita+eng',{logger:m=>{const label=m.status==='recognizing text'?'Riconoscimento del testo':'Preparazione del riconoscimento';showExtractionProgress(label,m.status||'Elaborazione in corso',m.status==='recognizing text'?m.progress*100:10)}});return (r.data.text||'').trim()}
async function extractTextFromFile(file){if(!file)return'';if(file.type==='text/plain')return await file.text();if(file.type==='application/pdf'||file.name.toLowerCase().endsWith('.pdf'))return await extractPdfText(file);if(file.type.startsWith('image/'))return await extractImageText(file);throw new Error('Questo formato non consente l’estrazione automatica del testo.')}
async function extractStoredDocumentText(id){const d=(state.documents||[]).find(x=>x.id===id),file=await getDocumentFile(id);if(!d||!file){alert('Il file non è disponibile su questo dispositivo.');return}try{const text=await extractTextFromFile(file);if(!text)throw new Error('Non è stato riconosciuto testo leggibile. Prova con una foto più nitida o inserisci il testo manualmente.');d.extractedText=text;d.extractionDate=new Date().toISOString();persist();guidedDocumentReading(d)}catch(err){const box=$('documentReader');box.classList.remove('hidden');box.innerHTML=`<div class="reader-head"><div><h3>Estrazione non completata</h3><p>${esc(err.message||String(err))}</p></div><button class="soft-btn" onclick="document.getElementById('documentReader').classList.add('hidden')">Chiudi</button></div><p>Puoi comunque modificare il documento e incollare il testo nel campo dedicato.</p>`}}

function guidedDocumentReading(d){const text=(d.extractedText||d.notes||'').trim();const box=$('documentReader');box.classList.remove('hidden');if(!text){box.innerHTML=`<div class="reader-head"><div><h3>Lettura guidata</h3><p>Non c’è ancora testo da organizzare per “${esc(d.name)}”.</p></div><button class="soft-btn" onclick="document.getElementById('documentReader').classList.add('hidden')">Chiudi</button></div><p>Modifica il documento e incolla il testo del referto nel campo dedicato.</p>`;box.scrollIntoView({behavior:'smooth'});return}
 const clean=text.replace(/\s+/g,' ').trim(),sentences=clean.split(/(?<=[.!?])\s+/).filter(x=>x.length>15),keywords=['controllo','visita','ecografia','cardiologo','cardiologia','esame','terapia','farmaco','follow-up','settimane','mesi','rivalutazione','consigliato','raccomandato'];
 const actions=sentences.filter(x=>keywords.some(k=>x.toLowerCase().includes(k))).slice(0,6);const dates=[...clean.matchAll(/\b(?:\d{1,2}[\/.-]\d{1,2}[\/.-]\d{2,4}|\d{1,2}\s+(?:gennaio|febbraio|marzo|aprile|maggio|giugno|luglio|agosto|settembre|ottobre|novembre|dicembre)\s+\d{4})\b/gi)].map(m=>m[0]).slice(0,6);const terms=[...new Set((clean.match(/\b[A-Za-zÀ-ÿ][A-Za-zÀ-ÿ-]{9,}\b/g)||[]).map(x=>x.toLowerCase()))].slice(0,10);
 box.innerHTML=`<div class="reader-head"><div><h3>📄 Lettura guidata: ${esc(d.name)}</h3><p>Organizzazione automatica del testo salvato.</p></div><button class="soft-btn" onclick="document.getElementById('documentReader').classList.add('hidden')">Chiudi</button></div><div class="reader-grid"><div class="reader-box"><h4>In sintesi</h4><p>${esc(sentences.slice(0,3).join(' ')||clean.slice(0,450))}</p></div><div class="reader-box"><h4>Indicazioni da verificare</h4>${actions.length?`<ul>${actions.map(x=>`<li>${esc(x)}</li>`).join('')}</ul>`:'<p>Nessuna indicazione operativa riconosciuta automaticamente.</p>'}</div><div class="reader-box"><h4>Date riconosciute</h4><p>${dates.length?dates.map(esc).join('<br>'):'Nessuna data riconosciuta.'}</p></div><div class="reader-box"><h4>Parole da chiedere al medico</h4><p>${terms.length?terms.map(esc).join(' · '):'Non sono stati individuati termini lunghi o tecnici.'}</p></div></div><div class="reader-warning"><strong>Importante:</strong> questa funzione aiuta a ordinare il testo e può sbagliare. Diagnosi, risultati e indicazioni devono essere spiegati e confermati dal professionista sanitario.</div>`;box.scrollIntoView({behavior:'smooth'})}
function renderDocuments(){
const docs=state.documents||[],complete=docs.filter(x=>x.status==='Completo'||x.done).length,missing=docs.filter(x=>x.status==='Manca'||(!x.status&&!x.done)).length,expiring=docs.filter(x=>x.expiry&&new Date(x.expiry+'T23:59:59')>=new Date()&&new Date(x.expiry+'T23:59:59')-new Date()<=30*86400000).length;
$('documentSummary').innerHTML=`<div class="doc-stat"><strong>${complete}</strong><small>completi</small></div><div class="doc-stat warning"><strong>${missing}</strong><small>mancanti</small></div><div class="doc-stat alert"><strong>${expiring}</strong><small>in scadenza</small></div>`;
const sorted=[...docs].sort((a,b)=>{const rank=x=>x.status==='Manca'?0:x.status==='Da aggiornare'?1:2;return rank(a)-rank(b)||(a.expiry||'9999').localeCompare(b.expiry||'9999')});
$('documentList').innerHTML=sorted.map(x=>{const visit=(state.visits||[]).find(v=>v.id===x.visitId);const status=x.status||(x.done?'Completo':'Manca');return `<article class="document-card ${status==='Completo'?'completed':''}"><div class="doc-icon">📄</div><div class="card-main"><div class="document-head"><div><h3>${esc(x.name)}</h3><small>${esc(x.category||'Documento')}</small></div><span class="badge doc-${status.toLowerCase().replaceAll(' ','-')}">${esc(status)}</span></div>${x.date?`<p><strong>Data documento:</strong> ${fmtDate(x.date)}</p>`:''}${x.expiry?`<p><strong>Scadenza:</strong> ${fmtDate(x.expiry)}</p>`:''}${visit?`<p><strong>Collegato a:</strong> ${esc(visit.title)} · ${fmtDate(visit.date)}</p>`:''}${x.notes?`<div class="document-notes">${esc(x.notes)}</div>`:''}${x.fileName?`<div class="document-file-meta"><span class="file-pill">📎 ${esc(x.fileName)}${x.fileSize?' · '+formatBytes(x.fileSize):''}</span>${x.driveUrl?'<span class="file-pill">☁️ Salvato su Drive</span>':'<span class="file-pill">📱 Solo dispositivo</span>'}</div>`:''}</div><div class="card-actions">${(x.fileName||x.driveUrl)?`<button data-doc-file="${x.id}" title="Apri file">👁️</button>`:''}${x.driveUrl?`<button data-doc-drive="${x.id}" title="Apri su Google Drive">☁️</button>`:''}${x.fileName?`<button data-doc-extract="${x.id}" title="Estrai testo automaticamente">🔎</button>`:''}${x.extractedText?`<button data-doc-read="${x.id}" title="Lettura guidata">🧭</button>`:''}<button data-doc-edit="${x.id}" title="Modifica">✏️</button><button data-doc-toggle="${x.id}" title="Cambia stato">${status==='Completo'?'↩️':'✅'}</button><button data-doc-del="${x.id}" title="Elimina">🗑️</button></div></article>`}).join('')||'<div class="empty-state">Nessun documento registrato.</div>';
document.querySelectorAll('[data-doc-file]').forEach(b=>b.onclick=()=>openStoredFile(b.dataset.docFile));document.querySelectorAll('[data-doc-drive]').forEach(b=>b.onclick=()=>{const d=state.documents.find(x=>x.id===b.dataset.docDrive);if(d?.driveUrl)window.open(d.driveUrl,'_blank')});document.querySelectorAll('[data-doc-extract]').forEach(b=>b.onclick=()=>extractStoredDocumentText(b.dataset.docExtract));document.querySelectorAll('[data-doc-read]').forEach(b=>b.onclick=()=>{const d=state.documents.find(x=>x.id===b.dataset.docRead);if(d)guidedDocumentReading(d)});document.querySelectorAll('[data-doc-toggle]').forEach(b=>b.onclick=()=>{const x=state.documents.find(d=>d.id===b.dataset.docToggle);x.status=(x.status==='Completo'?'Manca':'Completo');x.done=x.status==='Completo';persist()});
document.querySelectorAll('[data-doc-del]').forEach(b=>b.onclick=()=>{const id=b.dataset.docDel,d=state.documents.find(x=>x.id===id);if(!confirm('Eliminare il documento anche da Google Drive?'))return;state.documents=state.documents.filter(x=>x.id!==id);deleteDocumentFile(id).catch(()=>{});deleteDriveDocument(d);persist()});
document.querySelectorAll('[data-doc-edit]').forEach(b=>b.onclick=()=>{const x=state.documents.find(d=>d.id===b.dataset.docEdit);if(!x)return;$('documentId').value=x.id;$('documentName').value=x.name;$('documentCategory').value=x.category||'Altro';$('documentStatus').value=x.status||'Manca';$('documentDate').value=x.date||'';$('documentExpiry').value=x.expiry||'';$('documentVisit').value=x.visitId||'';$('documentNotes').value=x.notes||'';$('documentExtractedText').value=x.extractedText||'';$('documentFile').value='';$('documentSubmit').textContent='Salva modifiche';window.scrollTo({top:0,behavior:'smooth'})});
const select=$('documentVisit');if(select){const current=select.value;select.innerHTML='<option value="">Nessuna visita collegata</option>'+(state.visits||[]).map(v=>`<option value="${v.id}">${esc(v.title)} · ${fmtDate(v.date)}</option>`).join('');select.value=current}
}

function renderSimpleList(target,arr,key){$(target).innerHTML=arr.map(x=>`<article class="data-card"><div class="doc-icon">${key==='health'?'❤️':'🎓'}</div><div class="card-main"><h3>${esc(x.title)}</h3><small>${esc(x.type||x.year||'')}</small><p>${esc(x.notes||'')}</p></div><div class="card-actions"><button data-simple-del="${key}|${x.id}">🗑️</button></div></article>`).join('')||'<p>Nessun elemento inserito.</p>';document.querySelectorAll('[data-simple-del]').forEach(b=>b.onclick=()=>{const [k,id]=b.dataset.simpleDel.split('|');state[k]=state[k].filter(x=>x.id!==id);persist()})}
function renderBenefits(){$('benefitsList').innerHTML=state.benefits.map(x=>`<article class="data-card"><div class="doc-icon">🎁</div><div class="card-main"><h3>${esc(x.title)}</h3><span class="badge">${esc(x.status)}</span><p>${esc(x.notes||'')}</p></div><select data-benefit="${x.id}"><option ${x.status==='Da verificare'?'selected':''}>Da verificare</option><option ${x.status==='Da richiedere'?'selected':''}>Da richiedere</option><option ${x.status==='Richiesta inviata'?'selected':''}>Richiesta inviata</option><option ${x.status==='Approvata'?'selected':''}>Approvata</option></select></article>`).join('');document.querySelectorAll('[data-benefit]').forEach(s=>s.onchange=()=>{state.benefits.find(x=>x.id===s.dataset.benefit).status=s.value;persist()})}
function renderExpenses(){const total=state.expenses.reduce((a,x)=>a+Number(x.amount||0),0);$('expenseTotal').textContent=total.toLocaleString('it-IT',{style:'currency',currency:'EUR'});$('expenseList').innerHTML=[...state.expenses].sort((a,b)=>b.date.localeCompare(a.date)).map(x=>`<article class="data-card"><div class="doc-icon">💶</div><div class="card-main"><h3>${esc(x.title)}</h3><small>${fmtDate(x.date)} · ${esc(x.category)}</small></div><strong>${Number(x.amount).toLocaleString('it-IT',{style:'currency',currency:'EUR'})}</strong><div class="card-actions"><button data-exp-del="${x.id}">🗑️</button></div></article>`).join('')||'<p>Nessuna spesa registrata.</p>';document.querySelectorAll('[data-exp-del]').forEach(b=>b.onclick=()=>{state.expenses=state.expenses.filter(x=>x.id!==b.dataset.expDel);persist()})}
function birthPrepAvailable(item){if(state.profile?.mode!=='pregnancy')return true;return pregnancyInfo(state.profile.birthDate).daysLeft<=Number(item.daysBefore||999)}

function searchableItems(){
 const items=[];
 (state.visits||[]).forEach(x=>items.push({type:'Visita',icon:'🩺',title:x.title,text:[x.specialist,x.place,x.documents,x.questions,x.outcome].filter(Boolean).join(' · '),view:'visite'}));
 (state.documents||[]).forEach(x=>items.push({type:'Documento',icon:'📄',title:x.name,text:[x.category,x.status,x.notes].filter(Boolean).join(' · '),view:'documenti'}));
 (state.deadlines||[]).forEach(x=>items.push({type:'Appuntamento',icon:'📅',title:x.title,text:[fmtDate(x.date),x.category,x.notes].filter(Boolean).join(' · '),view:'calendario'}));
 (state.diary||[]).forEach(x=>items.push({type:'Diario',icon:'⭐',title:x.title,text:x.text||'',view:'diario'}));
 (state.pregnancyNotes||[]).forEach(x=>items.push({type:'Diario gravidanza',icon:'📘',title:`Settimana ${x.week}`,text:[x.memory,x.questions].filter(Boolean).join(' · '),view:'diario'}));
 libraryGuides.forEach(x=>items.push({type:'Guida',icon:'📚',title:x.title,text:[x.category,x.summary,...x.sections.flat()].join(' · '),view:'biblioteca',guideId:x.id}));
 journeyItems.forEach(x=>items.push({type:'Checklist',icon:'✅',title:x.title,text:[x.group,x.description,x.meta].join(' · '),view:'checklist'}));
 return items;
}
function globalSearch(q){q=(q||'').trim().toLowerCase();if(q.length<2)return[];return searchableItems().filter(x=>(x.title+' '+x.text+' '+x.type).toLowerCase().includes(q)).slice(0,20)}
function renderGlobalSearch(){const box=$('globalSearchResults'),input=$('globalSearchInput');if(!box||!input)return;const q=input.value;const list=globalSearch(q);if(q.trim().length<2){box.innerHTML='<p class="muted">Scrivi almeno due lettere.</p>';return}box.innerHTML=list.map(x=>`<button class="global-result" data-result-view="${x.view}" data-result-guide="${x.guideId||''}"><span>${x.icon}</span><div><small>${esc(x.type)}</small><strong>${esc(x.title)}</strong><p>${esc((x.text||'').slice(0,120))}</p></div></button>`).join('')||'<div class="empty-state">Nessun risultato trovato.</div>';document.querySelectorAll('[data-result-view]').forEach(b=>b.onclick=()=>{showView(b.dataset.resultView);if(b.dataset.resultGuide)setTimeout(()=>openGuide(b.dataset.resultGuide),100)})}
function upcomingVisit(){return [...(state.visits||[])].filter(v=>v.date>=today()).sort((a,b)=>(a.date+a.time).localeCompare(b.date+b.time))[0]}
function missingDocuments(){return (state.documents||[]).filter(d=>(d.status||'Manca')!=='Completo')}
function prepareVisitText(v){if(!v)return 'Non risultano visite future. Puoi aggiungerne una nella sezione Visite.';const linked=(state.documents||[]).filter(d=>d.visitId===v.id&&d.status==='Completo');const questions=[v.questions,...(state.pregnancyNotes||[]).map(n=>n.questions)].filter(Boolean).join('\n');const docs=[v.documents,...linked.map(d=>d.name)].filter(Boolean);return `Prepariamo “${v.title}” del ${fmtDate(v.date)}${v.time?' alle '+v.time:''}.\n\n📄 Da portare: ${docs.length?docs.join(', '):'controlla referti precedenti, tessera sanitaria e documenti richiesti dalla struttura'}.\n\n❓ Domande annotate: ${questions||'non risultano domande salvate; scrivi ora i tre dubbi più importanti'}.\n\n📍 ${[v.specialist,v.place].filter(Boolean).join(' · ')||'Verifica luogo e specialista.'}`}
function assistantReply(question){const q=question.toLowerCase();if(q.includes('prepara')&&q.includes('visita')){const id=(question.match(/[a-z0-9-]{8,}$/i)||[])[0];return prepareVisitText((state.visits||[]).find(v=>v.id===id)||upcomingVisit())}if(q.includes('document')){const miss=missingDocuments();return miss.length?`Ci sono ${miss.length} documenti non completi:\n${miss.slice(0,8).map(d=>'• '+d.name+' — '+(d.status||'Manca')).join('\n')}${miss.length>8?'\n• e altri '+(miss.length-8):''}`:'Tutti i documenti registrati risultano completi.'}if(q.includes('settimana')||q.includes('prossim')||q.includes('cosa devo')){const v=upcomingVisit();const due=(state.deadlines||[]).filter(d=>d.date>=today()).sort((a,b)=>a.date.localeCompare(b.date)).slice(0,3);const miss=missingDocuments().slice(0,3);return [`Per i prossimi giorni ti suggerisco:`,v?`• Preparare la visita “${v.title}” del ${fmtDate(v.date)}.`:'• Controllare se ci sono visite da registrare.',...due.map(d=>`• ${d.title}: ${fmtDate(d.date)}.`),...miss.map(d=>`• Completare il documento “${d.name}”.`)].join('\n')}if(q.includes('guida')||q.includes('leggere')){const g=suggestedGuide();return `Ti consiglio “${g.title}” (${g.minutes} minuti). ${g.summary}`}const results=globalSearch(question);if(results.length)return `Ho trovato ${results.length} elementi collegati:\n${results.slice(0,6).map(x=>`• ${x.type}: ${x.title}`).join('\n')}\n\nUsa anche la ricerca globale per aprirli.`;return 'Non ho trovato un collegamento preciso nei dati salvati. Prova con parole come visita, documenti, cuore, 104, gravidanza o guida.'}
function askAssistant(question){if(!question?.trim())return;state.assistantMessages=state.assistantMessages||[];state.assistantMessages.push({id:uid(),role:'user',text:question.trim(),date:new Date().toISOString()});state.assistantMessages.push({id:uid(),role:'assistant',text:assistantReply(question.trim()),date:new Date().toISOString()});if(state.assistantMessages.length>30)state.assistantMessages=state.assistantMessages.slice(-30);persist(false);setTimeout(()=>{const m=$('assistantMessages');if(m)m.scrollTop=m.scrollHeight},20)}
function renderAssistant(){const box=$('assistantMessages');if(!box)return;state.assistantMessages=state.assistantMessages||[];if(!state.assistantMessages.length)box.innerHTML='<div class="assistant-empty"><span>💙</span><strong>Da dove cominciamo?</strong><p>Scegli un suggerimento oppure scrivi una domanda.</p></div>';else box.innerHTML=state.assistantMessages.map(m=>`<div class="message ${m.role}"><div>${esc(m.text).replaceAll('\n','<br>')}</div></div>`).join('');renderGlobalSearch()}

function renderBirthPrep(){
 const section=$('preparazione');if(!section)return;
 const isPreg=state.profile?.mode==='pregnancy';$('birthPrepIntro').textContent=isPreg?`Mancano circa ${pregnancyInfo(state.profile.birthDate).daysLeft} giorni alla data presunta del parto. Le attività vengono proposte al momento giusto.`:'Una checklist personalizzabile per organizzare il rientro e le prime settimane.';
 state.birthPrep=state.birthPrep||defaultBirthPrep.map(x=>({...x,done:false,custom:false,notes:''}));
 const filter=$('birthPrepFilter')?.value||'all';const items=state.birthPrep.filter(x=>filter==='all'||x.category===filter);
 const available=items.filter(birthPrepAvailable),later=items.filter(x=>!birthPrepAvailable(x));
 const renderItem=x=>`<article class="prep-card ${x.done?'completed':''}"><label class="prep-check"><input type="checkbox" data-prep-check="${x.id}" ${x.done?'checked':''}><span></span></label><div class="card-main"><div class="prep-head"><h3>${esc(x.title)}</h3><span class="badge ${x.priority==='Alta'?'urgent':''}">${esc(x.category)}</span></div><small>${x.custom?'Attività personalizzata':`Consigliata entro ${x.daysBefore} giorni dal parto`}</small>${x.notes?`<p>${esc(x.notes)}</p>`:''}</div><button class="icon-btn" data-prep-del="${x.id}" aria-label="Elimina">🗑️</button></article>`;
 $('birthPrepList').innerHTML=available.map(renderItem).join('')||'<div class="empty-state">Nessuna attività in questa categoria.</div>';
 $('birthPrepLater').innerHTML=later.length?`<details class="panel"><summary>Attività che compariranno più avanti (${later.length})</summary><div class="prep-list later-list">${later.map(renderItem).join('')}</div></details>`:'';
 const done=state.birthPrep.filter(x=>x.done).length,total=state.birthPrep.length,pct=total?Math.round(done/total*100):0;$('birthPrepProgress').style.width=pct+'%';$('birthPrepProgressText').textContent=`${done} di ${total} attività completate · ${pct}%`;
 document.querySelectorAll('[data-prep-check]').forEach(c=>c.onchange=()=>{const x=state.birthPrep.find(i=>i.id===c.dataset.prepCheck);if(x){x.done=c.checked;persist()}});
 document.querySelectorAll('[data-prep-del]').forEach(b=>b.onclick=()=>{const x=state.birthPrep.find(i=>i.id===b.dataset.prepDel);if(!x?.custom&&!confirm('Eliminare questa attività dalla checklist?'))return;state.birthPrep=state.birthPrep.filter(i=>i.id!==b.dataset.prepDel);persist()});
}
function renderDiagnosisSupport(){
 const box=$('diagnosisSupportList');if(!box)return;state.diagnosisSupport=state.diagnosisSupport||defaultDiagnosisSupport.map(x=>({...x,notes:''}));
 const done=state.diagnosisSupport.filter(x=>x.done).length,total=state.diagnosisSupport.length,pct=total?Math.round(done/total*100):0;
 $('diagnosisProgressText').textContent=`${done} di ${total} passi completati · ${pct}%`;$('diagnosisProgress').style.width=pct+'%';
 box.innerHTML=state.diagnosisSupport.map(x=>`<article class="support-step ${x.done?'completed':''}"><label class="check-row"><input type="checkbox" data-diag-check="${x.id}" ${x.done?'checked':''}><span><small>${esc(x.category)}</small><strong>${esc(x.title)}</strong><p>${esc(x.description)}</p></span></label><textarea data-diag-note="${x.id}" placeholder="Aggiungi una nota personale">${esc(x.notes||'')}</textarea></article>`).join('');
 document.querySelectorAll('[data-diag-check]').forEach(c=>c.onchange=()=>{const x=state.diagnosisSupport.find(i=>i.id===c.dataset.diagCheck);if(x){x.done=c.checked;persist()}});
 document.querySelectorAll('[data-diag-note]').forEach(t=>t.onchange=()=>{const x=state.diagnosisSupport.find(i=>i.id===t.dataset.diagNote);if(x){x.notes=t.value.trim();persist()}});
}
function renderDiary(){$('diaryList').innerHTML=[...state.diary].sort((a,b)=>b.date.localeCompare(a.date)).map(x=>`<article class="data-card"><div class="doc-icon">⭐</div><div class="card-main"><h3>${esc(x.title)}</h3><small>${fmtDate(x.date)}</small><p>${esc(x.text)}</p></div><div class="card-actions"><button data-dia-del="${x.id}">🗑️</button></div></article>`).join('')||'<p>Il diario è ancora vuoto.</p>';document.querySelectorAll('[data-dia-del]').forEach(b=>b.onclick=()=>{state.diary=state.diary.filter(x=>x.id!==b.dataset.diaDel);persist()})}
function renderPregnancyDiary(){
const preg=state.profile?.mode==='pregnancy',box=$('pregnancyDiaryBox'),standard=$('standardDiaryBox');if(!box||!standard)return;
box.classList.toggle('hidden',!preg);standard.classList.toggle('hidden',preg);$('diarySubtitle').textContent=preg?'La storia dell’attesa, settimana dopo settimana.':'Traguardi, ricordi e progressi.';if(!preg)return;
const info=pregnancyInfo(state.profile.birthDate);$('diaryWeekTitle').textContent=`${info.week}ª settimana di gravidanza`;
if(!$('pregDiaryDate').value)$('pregDiaryDate').value=new Date().toISOString().slice(0,10);if(!$('pregDiaryWeek').value)$('pregDiaryWeek').value=info.week;
const entries=[...(state.pregnancyNotes||[])].sort((a,b)=>(b.date||'').localeCompare(a.date||''));
$('pregnancyDiaryList').innerHTML=entries.map(x=>`<article class="weekly-diary-card"><div class="week-badge"><strong>${esc(x.week)}</strong><small>settimana</small></div><div class="card-main"><div class="weekly-head"><h3>${fmtDate(x.date)}</h3><button data-preg-dia-del="${x.id}" aria-label="Elimina">🗑️</button></div><div class="mood-row"><span>🤰 ${esc(x.motherMood||'—')}</span><span>👨 ${esc(x.fatherMood||'—')}</span></div><p class="memory-text">${esc(x.memory)}</p>${x.questions?`<div class="doctor-questions"><strong>Domande per il medico</strong><p>${esc(x.questions)}</p></div>`:''}</div></article>`).join('')||'<div class="empty-state">Nessun ricordo ancora salvato. Iniziate dalla settimana che state vivendo.</div>';
document.querySelectorAll('[data-preg-dia-del]').forEach(b=>b.onclick=()=>{state.pregnancyNotes=(state.pregnancyNotes||[]).filter(x=>x.id!==b.dataset.pregDiaDel);persist()})}
$('librarySearch').oninput=renderLibrary;$('libraryCategory').onchange=renderLibrary;$('libraryFavoritesOnly').onchange=renderLibrary;
$('profileForm').onsubmit=e=>{e.preventDefault();state.profile={childName:$('childName').value.trim(),mode:$('journeyMode').value,familyCode:(window.PDP_CLOUD?.getFamilyId?.()||$('familyCode').value.trim().toUpperCase()),birthDate:$('birthDate').value};if(!state.members?.length){const id='owner-'+state.profile.familyCode;state.members=[{id,name:'Genitore',role:'Genitore',permission:'owner'}];state.activeMemberId=id}persist(false);renderAll();syncToGoogle(false)};
document.querySelectorAll('[data-view]').forEach(b=>b.onclick=()=>showView(b.dataset.view));document.querySelectorAll('[data-view-target]').forEach(b=>b.onclick=()=>showView(b.dataset.viewTarget));$('menuBtn').onclick=toggleMenu;$('menuBackdrop').onclick=()=>{closeMenu();closeQuickAdd()};$('phaseFilter').onchange=renderJourney;$('syncBtn').onclick=()=>syncToGoogle(true);$('reloadBtn').onclick=()=>loadFromGoogle(true);
$('visitForm').onsubmit=e=>{e.preventDefault();const visit={id:uid(),title:$('visitTitle').value.trim(),date:$('visitDate').value,time:$('visitTime').value,specialist:$('visitSpecialist').value.trim(),place:$('visitPlace').value.trim(),documents:$('visitDocuments').value.trim(),questions:$('visitQuestions').value.trim(),outcome:$('visitOutcome').value.trim()};state.visits=state.visits||[];state.visits.push(visit);if($('visitAddCalendar').checked){state.deadlines.push({id:'visit-'+visit.id,title:visit.title,date:visit.date,time:visit.time,category:'Salute',notes:[visit.specialist,visit.place].filter(Boolean).join(' · ')})}e.target.reset();$('visitAddCalendar').checked=true;persist()};
$('deadlineForm').onsubmit=e=>{e.preventDefault();state.deadlines.push({id:uid(),title:$('deadlineTitle').value.trim(),date:$('deadlineDate').value,time:$('deadlineTime').value,category:$('deadlineCategory').value,notes:$('deadlineNotes').value.trim()});e.target.reset();persist()};
$('documentForm').onsubmit=async e=>{e.preventDefault();const id=$('documentId').value||uid(),existing=state.documents.find(x=>x.id===id)||{},file=$('documentFile').files[0];let extracted=$('documentExtractedText').value.trim(),driveInfo=null;if(file&&!extracted){try{extracted=await extractTextFromFile(file)}catch(err){const proceed=confirm('Estrazione automatica non completata: '+(err.message||err)+'\n\nVuoi salvare comunque il documento?');if(!proceed)return}}if(file){try{await saveDocumentFile(id,file)}catch(err){alert('Non è stato possibile salvare il file sul dispositivo. Proverò comunque a salvarlo su Google Drive.')}try{driveInfo=await uploadDocumentToDrive(id,file,$('documentName').value.trim(),existing.driveFileId||'')}catch(err){const proceed=confirm('Salvataggio su Google Drive non riuscito: '+(err.message||err)+'\n\nVuoi conservare comunque il documento soltanto su questo dispositivo?');if(!proceed)return}}const item={...existing,id,name:$('documentName').value.trim(),category:$('documentCategory').value,status:$('documentStatus').value,done:$('documentStatus').value==='Completo',date:$('documentDate').value,expiry:$('documentExpiry').value,visitId:$('documentVisit').value,notes:$('documentNotes').value.trim(),extractedText:extracted,fileName:file?file.name:(existing.fileName||''),fileType:file?file.type:(existing.fileType||''),fileSize:file?file.size:(existing.fileSize||0),driveFileId:driveInfo?.fileId||existing.driveFileId||'',driveUrl:driveInfo?.fileUrl||existing.driveUrl||'',driveUploadedAt:driveInfo?.uploadedAt||existing.driveUploadedAt||''};const idx=state.documents.findIndex(x=>x.id===id);if(idx>=0)state.documents[idx]=item;else state.documents.push(item);e.target.reset();$('documentId').value='';$('documentSubmit').textContent='Aggiungi documento';persist();if(driveInfo)alert('Documento salvato sul dispositivo, su Google Drive e registrato nel Foglio Google.');};
$('healthForm').onsubmit=e=>{e.preventDefault();state.health.push({id:uid(),title:$('healthTitle').value.trim(),type:$('healthType').value,notes:$('healthNotes').value.trim()});e.target.reset();persist()};
$('schoolForm').onsubmit=e=>{e.preventDefault();state.school.push({id:uid(),title:$('schoolTitle').value.trim(),year:$('schoolYear').value.trim(),notes:$('schoolNotes').value.trim()});e.target.reset();persist()};
$('expenseForm').onsubmit=e=>{e.preventDefault();state.expenses.push({id:uid(),title:$('expenseTitle').value.trim(),amount:Number($('expenseAmount').value),date:$('expenseDate').value,category:$('expenseCategory').value});e.target.reset();persist()};
$('diaryForm').onsubmit=e=>{e.preventDefault();state.diary.push({id:uid(),title:$('diaryTitle').value.trim(),date:$('diaryDate').value,text:$('diaryText').value.trim()});e.target.reset();persist()};
$('pregnancyDiaryForm').onsubmit=e=>{e.preventDefault();state.pregnancyNotes=state.pregnancyNotes||[];state.pregnancyNotes.push({id:uid(),date:$('pregDiaryDate').value,week:Number($('pregDiaryWeek').value),motherMood:$('pregDiaryMother').value,fatherMood:$('pregDiaryFather').value,memory:$('pregDiaryMemory').value.trim(),questions:$('pregDiaryQuestions').value.trim()});e.target.reset();$('pregDiaryDate').value=new Date().toISOString().slice(0,10);$('pregDiaryWeek').value=pregnancyInfo(state.profile.birthDate).week;persist();};
$('birthPrepForm').onsubmit=e=>{e.preventDefault();state.birthPrep=state.birthPrep||[];state.birthPrep.push({id:uid(),category:$('birthPrepCategory').value,title:$('birthPrepTitle').value.trim(),daysBefore:Number($('birthPrepDays').value||999),priority:$('birthPrepPriority').value,done:false,custom:true,notes:$('birthPrepNotes').value.trim()});e.target.reset();$('birthPrepDays').value='30';persist()};
$('birthPrepFilter').onchange=renderBirthPrep;
$('editProfileBtn').onclick=()=>{if(!state.profile)return;$('childName').value=state.profile.childName;if($('familyCode'))$('familyCode').value=state.profile.familyCode||'';$('birthDate').value=state.profile.birthDate;$('journeyMode').value=state.profile.mode||'born';updateDateLabel();$('app').classList.add('hidden');$('onboarding').classList.remove('hidden')};if($('exportJsonBtn'))$('exportJsonBtn').onclick=exportJson;if($('exportCsvBtn'))$('exportCsvBtn').onclick=exportCsv;if($('retrySyncBtn'))$('retrySyncBtn').onclick=()=>performCloudSync(true);
$('resetBtn').onclick=()=>{if(confirm('Cancellare tutti i dati salvati su questo dispositivo?')){localStorage.removeItem('pdp_state');location.reload()}};
window.addEventListener('beforeinstallprompt',e=>{e.preventDefault();deferredPrompt=e;$('installBtn').classList.remove('hidden')});$('installBtn').onclick=async()=>{if(deferredPrompt){deferredPrompt.prompt();await deferredPrompt.userChoice;deferredPrompt=null}};

if($('assistantForm'))$('assistantForm').onsubmit=e=>{e.preventDefault();const q=$('assistantInput').value;$('assistantInput').value='';askAssistant(q)};
document.querySelectorAll('[data-assistant-question]').forEach(b=>b.onclick=()=>askAssistant(b.dataset.assistantQuestion));
if($('globalSearchInput'))$('globalSearchInput').oninput=renderGlobalSearch;


function closeMenu(){$('sidebar')?.classList.remove('open');$('menuBackdrop')?.classList.add('hidden')}
function toggleMenu(){const opening=!$('sidebar').classList.contains('open');$('sidebar').classList.toggle('open',opening);$('menuBackdrop').classList.toggle('hidden',!opening)}
function openQuickAdd(){$('quickAddSheet').classList.remove('hidden');$('menuBackdrop').classList.remove('hidden')}
function closeQuickAdd(){$('quickAddSheet')?.classList.add('hidden');if(!$('sidebar')?.classList.contains('open'))$('menuBackdrop')?.classList.add('hidden')}
function setBadge(id,value){const el=$(id);if(!el)return;el.textContent=value;el.classList.toggle('hidden',!value)}
function renderProfessionalNav(){if(!state.profile)return;const preg=state.profile.mode==='pregnancy';document.querySelectorAll('.pregnancy-only').forEach(x=>x.classList.toggle('hidden',!preg));document.querySelectorAll('.born-only').forEach(x=>x.classList.toggle('hidden',preg));$('sidebarChildName').textContent=state.profile.childName;$('sidebarJourneyLabel').textContent=preg?pregnancyLabel(state.profile.birthDate):ageText(state.profile.birthDate);const today=new Date().toISOString().slice(0,10);setBadge('badgeCalendario',(state.deadlines||[]).filter(x=>x.date>=today).length);setBadge('badgeVisite',(state.visits||[]).filter(x=>x.date>=today).length);setBadge('badgeDocumenti',(state.documents||[]).filter(x=>x.status==='Manca'||x.status==='Da aggiornare').length);const all=preg?activeItems():journeyItems;setBadge('badgeChecklist',all.filter(x=>!state.completed.includes(x.id)).length)}
function applyPreferences(){const p=state.preferences||{};document.body.classList.toggle('theme-dark',p.theme==='dark'||(p.theme==='system'&&matchMedia('(prefers-color-scheme: dark)').matches));document.body.classList.toggle('high-contrast',!!p.highContrast);document.body.classList.toggle('large-icons',!!p.largeIcons);document.body.classList.toggle('text-large',p.textSize==='large');document.body.classList.toggle('text-xlarge',p.textSize==='xlarge');if($('themeSelect'))$('themeSelect').value=p.theme||'system';if($('textSizeSelect'))$('textSizeSelect').value=p.textSize||'normal';if($('highContrastToggle'))$('highContrastToggle').checked=!!p.highContrast;if($('largeIconsToggle'))$('largeIconsToggle').checked=!!p.largeIcons}
function permissionLabel(p){return p==='owner'?'Amministratore':p==='editor'?'Può modificare':'Solo lettura'}
function applyMemberPermission(){const cloudMember=window.PDP_CLOUD?.getMember?.();const active=cloudMember||(state.members||[]).find(x=>x.id===state.activeMemberId),readOnly=active?.permission==='viewer';document.body.classList.toggle('read-only-mode',!!readOnly);document.querySelectorAll('form input,form select,form textarea,form button[type="submit"],.danger-btn').forEach(el=>{if(el.closest('#memberForm')||el.id==='navSearch')return;el.disabled=!!readOnly});if(readOnly&&$('syncStatus'))$('syncStatus').textContent='Modalità sola lettura'}
function renderFamilyMembers(){
 const box=$('familyMembersList');if(!box)return;state.members=state.members||[];
 const me=window.PDP_CLOUD?.getMember?.();const admin=['owner','admin'].includes(me?.permission);
 box.innerHTML=state.members.map(m=>`<article class="member-card ${m.id===state.activeMemberId?'active-member':''}"><span class="member-initial">${esc((m.name||'?').slice(0,1).toUpperCase())}</span><div class="grow"><strong>${esc(m.name)}</strong><small>${esc(m.role)} · ${permissionLabel(m.permission)}${m.email?' · '+esc(m.email):''}</small></div>${m.id===state.activeMemberId?'<span class="nav-badge">Tu</span>':admin?`<button class="mini-btn" data-member-edit="${m.id}">Gestisci</button>`:''}</article>`).join('')||'<p class="privacy-note">Nessun account familiare caricato.</p>';
 document.querySelectorAll('[data-member-edit]').forEach(b=>b.onclick=async()=>{const m=state.members.find(x=>x.id===b.dataset.memberEdit);if(!m)return;const choice=prompt(`Permesso per ${m.name}: owner, admin, editor o viewer`,m.permission||'editor');if(!choice)return;if(!['owner','admin','editor','viewer'].includes(choice))return alert('Permesso non valido.');try{await window.PDP_CLOUD.updateMember(m.id,{permission:choice});activity('Permesso modificato',`${m.name}: ${choice}`);await window.PDP_CLOUD.reload()}catch(e){alert(e.message)}});
}
function renderActivityLog(){const box=$('activityLog');if(!box)return;const rows=(state.activityLog||[]).slice(0,30);box.innerHTML=rows.map(x=>`<article class="activity-row"><span>•</span><div><strong>${esc(x.action)}</strong><small>${esc(x.by||'Utente')} · ${new Date(x.at).toLocaleString('it-IT')}${x.detail?' · '+esc(x.detail):''}</small></div></article>`).join('')||'<p class="privacy-note">Nessuna attività registrata.</p>'}
function downloadBlob(name,type,content){const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([content],{type}));a.download=name;document.body.appendChild(a);a.click();setTimeout(()=>{URL.revokeObjectURL(a.href);a.remove()},500)}
function exportJson(){downloadBlob(`passo-dopo-passo-backup-${new Date().toISOString().slice(0,10)}.json`,'application/json',JSON.stringify(snapshot(),null,2));activity('Backup esportato','Formato JSON');saveLocal();renderActivityLog()}
function exportCsv(){const rows=[['Sezione','Titolo','Data','Stato','Note']];(state.visits||[]).forEach(x=>rows.push(['Visita',x.title||'',x.date||'',x.notes?'Completata':'Da preparare',x.notes||'']));(state.documents||[]).forEach(x=>rows.push(['Documento',x.name||'',x.date||'',x.status||'',x.notes||'']));(state.deadlines||[]).forEach(x=>rows.push(['Calendario',x.title||'',x.date||'','',x.notes||'']));const csv=rows.map(r=>r.map(v=>'"'+String(v??'').replace(/"/g,'""')+'"').join(';')).join('\n');downloadBlob(`passo-dopo-passo-${new Date().toISOString().slice(0,10)}.csv`,'text/csv;charset=utf-8','\ufeff'+csv);activity('Dati esportati','Formato CSV');saveLocal();renderActivityLog()}
$('quickAddBtn').onclick=openQuickAdd;$('quickAddClose').onclick=closeQuickAdd;document.querySelectorAll('[data-quick-view]').forEach(b=>b.onclick=()=>showView(b.dataset.quickView));
$('themeSelect').onchange=e=>{state.preferences.theme=e.target.value;persist()};$('textSizeSelect').onchange=e=>{state.preferences.textSize=e.target.value;persist()};$('highContrastToggle').onchange=e=>{state.preferences.highContrast=e.target.checked;persist()};$('largeIconsToggle').onchange=e=>{state.preferences.largeIcons=e.target.checked;persist()};
document.querySelectorAll('.nav-group-toggle').forEach(b=>b.onclick=()=>{const g=b.closest('.nav-group');g.classList.toggle('collapsed');b.setAttribute('aria-expanded',String(!g.classList.contains('collapsed')))});
$('navSearch').oninput=e=>{const q=e.target.value.trim().toLowerCase();document.querySelectorAll('.nav-item').forEach(x=>{const phaseHidden=(x.classList.contains('pregnancy-only')&&state.profile?.mode!=='pregnancy')||(x.classList.contains('born-only')&&state.profile?.mode==='pregnancy');x.classList.toggle('hidden',phaseHidden||!!q&&!((x.dataset.label||x.textContent).toLowerCase().includes(q)))});document.querySelectorAll('.nav-group').forEach(g=>{const visible=[...g.querySelectorAll('.nav-item')].some(x=>!x.classList.contains('hidden'));g.classList.toggle('hidden',!visible)})};

const APP_VERSION='4.1.0';let waitingWorker=null;let refreshing=false;
function showUpdate(worker){waitingWorker=worker;$('updateBanner')?.classList.remove('hidden')}
async function registerUpdater(){
  if(!('serviceWorker'in navigator))return;
  try{
    const registration=await navigator.serviceWorker.register('service-worker.js',{updateViaCache:'none'});
    if(registration.waiting&&navigator.serviceWorker.controller)showUpdate(registration.waiting);
    registration.addEventListener('updatefound',()=>{
      const worker=registration.installing;if(!worker)return;
      worker.addEventListener('statechange',()=>{if(worker.state==='installed'&&navigator.serviceWorker.controller)showUpdate(worker)});
    });
    $('checkUpdateBtn').onclick=async()=>{const btn=$('checkUpdateBtn');btn.disabled=true;btn.textContent='Controllo…';try{await registration.update();if(!registration.waiting)btn.textContent='App aggiornata'}catch(e){btn.textContent='Controllo non riuscito'}setTimeout(()=>{btn.disabled=false;btn.textContent='Controlla aggiornamenti'},1800)};
    setInterval(()=>registration.update().catch(()=>{}),60*60*1000);
  }catch(e){console.warn('Aggiornamento PWA non disponibile',e)}
}
$('appVersion').textContent=APP_VERSION;
$('applyUpdateBtn').onclick=()=>{if(waitingWorker){$('applyUpdateBtn').disabled=true;$('applyUpdateBtn').textContent='Aggiornamento…';waitingWorker.postMessage({type:'SKIP_WAITING'})}};
$('updateLaterBtn').onclick=()=>$('updateBanner').classList.add('hidden');
navigator.serviceWorker?.addEventListener('controllerchange',()=>{if(refreshing)return;refreshing=true;location.reload()});
window.addEventListener('load',registerUpdater);
window.addEventListener('online',()=>{if(state.syncMeta?.pending)performCloudSync(false)});window.addEventListener('offline',()=>setSyncStatus('Offline: copia locale','error'));
function updateDateLabel(){const preg=$('journeyMode').value==='pregnancy';$('birthDateLabel').childNodes[0].nodeValue=preg?'Data presunta del parto':'Data di nascita'}$('journeyMode').onchange=updateDateLabel;updateDateLabel();
window.PDP_APP={
 getState:()=>snapshot(),
 replaceState:(data,options={})=>{state=Object.assign(emptyState(),data||{});state.preferences={...emptyState().preferences,...(state.preferences||{})};state.syncMeta={...emptyState().syncMeta,...(state.syncMeta||{})};state.activityLog=state.activityLog||[];state.members=state.members||[];state.documents=(state.documents||[]).map(d=>({...d,status:d.status||(d.done?'Completo':'Manca'),done:(d.status?d.status==='Completo':!!d.done),expiry:d.expiry||'',visitId:d.visitId||'',notes:d.notes||'',fileName:d.fileName||'',fileType:d.fileType||'',fileSize:d.fileSize||0,extractedText:d.extractedText||'',driveFileId:d.driveFileId||'',driveUrl:d.driveUrl||'',driveUploadedAt:d.driveUploadedAt||''}));localStorage.setItem('pdp_state',JSON.stringify(state));renderAll();if(options.fromCloud){state.syncMeta={...state.syncMeta,status:'ok',pending:false,error:'',lastSuccess:options.updatedAt||new Date().toISOString(),revision:options.revision||state.syncMeta.revision||0};saveLocal();refreshSyncUi()}},
 persist:()=>persist(true)
};
renderAll();if(state.profile&&!window.PDP_CLOUD?.isConfigured?.()){setSyncStatus(apiConfigured()?'Google collegato':'Configura Apps Script',apiConfigured()?'ok':'error');loadFromGoogle(false)}
